### ISSUE TITLE
Throwing "-bash: shell_session_update: command not found"

### ISSUE THREAD

**Issue by rafaelliu** [asdf-vm/asdf#333] opened 2018-06-07 01:31 UTC
### Steps to reproduce

1. Install latest version `0.5.0`
2. Open a new login shell

### Expected behavior

```
Last login: Wed Jun  6 18:25:39 on ttys009
 ~ $
```

### Actual behavior

```
Last login: Wed Jun  6 18:25:39 on ttys009
-bash: shell_session_update: command not found
 ~ $
```

### Environment

```
$ asdf --version
v0.5.0

$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin16.7.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1408

```

**Comment by Stratus3D** [comment] 2018-06-18 14:32
I do not experience this on OSX. Can you verify this is due to asdf? A subshell should not affect`shell_session_update`.

**Comment by rafaelliu** [comment] 2018-06-18 23:30
After some digging I confirm the `shell_session_update` error is actually an issue with older versions of RVM[1]. If an affected version is installed and non-Apple terminal is used, asdf can trigger the bug and PATH will be messed up.

The PATH bug is actually a separate issue by itself (as explained in the [pull request comment](https://github.com/asdf-vm/asdf/pull/334#issuecomment-395273949)) and can happen in other cases too.

[1] Issue: https://github.com/rvm/rvm/issues/3782. Documenting this since I didn't find it anywhere else:
1. Mac OS has a feature that saves and restores terminal sessions. It uses a set of `shell_session_*`  functions to do so. They are defined in `/etc/bashrc_Apple_Terminal` script which among other things defines a `trap` on EXIT to call the `shell_session_update` and save the session.
2. That file is sourced by`/etc/bashrc` though `/etc/bashrc_$TERM_PROGRAM`. Which works fine with built-in Terminal app, but not when on iTerm.
3. RVM didn't account for that and was trapping EXIT on its teardown routine and calling `shell_session_update` (fixed [here](https://github.com/rvm/rvm/commit/cbc4488028ccc682a872034ba823f61bf2d9cf6d))
4. Changing directories would invoke RVM scripts and after subshell exited, RVM would call the undefined function and the error would happen

**Comment by Stratus3D** [comment] 2018-07-14 13:39
Closing this issue since it is not a bug in asdf. I will merge the related PR though.

**Closed by Stratus3D** 2018-07-14 13:39 UTC
