### ISSUE TITLE
bug: the command `asdf list all ruby` hangs in Terminal on MacOS Monterey

### ISSUE THREAD

**Issue by claresudbery** [asdf-vm/asdf#1179] opened 2022-03-08 09:31 UTC
### Describe the Bug

When I run `asdf list all ruby` I get no response - it just sits there and appears to hang. I've been waiting 5 minutes now.
I'm on MacOS Monterey.
When I run `asdf list ruby` that works fine.
I'm on asdf v 0.9.0

### Steps to Reproduce

run `asdf list all ruby` in Terminal in MAcOS Monterey

### Expected Behaviour

I expect to see list of all Ruby versions available to install

### Actual Behaviour

It just sits there. No feedback, nothing.

### Environment

```shell
OS:
Darwin claresuberysmbp.lan 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.9.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
ruby                         https://github.com/asdf-vm/asdf-ruby.git master de49662
```

### asdf plugins affected (if relevant)

ruby

**Comment by JacobAlexander** [comment] 2022-03-17 23:08
Works for me, I've started using asdf a day ago on Monterey.

**Comment by HashNuke** [comment] 2022-04-15 10:15
I just tried running the following command:

```
asdf list all ruby
```

* The command output is as expected - lists all the ruby versions possible for install.
* asdf-ruby commit sha: `de49662`
* My local asdf commit sha `2a538fe6`
* I am on Mac OS 11.6.4

Since my asdf version was old, I also updated to latest master `448f750891a` and tried the command. Still works as expected. Since another user confirmed the same output, I'll close this issue for now.

@claresudbery
* Can you please try updating to the latest asdf and asdf-ruby versions?
* If the error still occurs, please do share details like the issue description, along with the asdf version too. We'll reopen this ticket and look into it again.

**Closed by HashNuke** 2022-04-15 10:15 UTC
Labels: bug

**Comment by scotty-g** [comment] 2022-07-01 21:04
I've run into this as well. It's annoying in that `asdf` will work for a time, then stop working. A reboot will usually make it work again so it's possible something is wrong with the system.

In any case, the details:
```
OS:
Darwin redact 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

ASDF Version:
$ asdf version
v0.10.2
```

I've tracked it down to the `read` builtin call [here](https://github.com/asdf-vm/asdf/blob/master/lib/functions/versions.bash#L111). This call hangs. It doesn't matter which plugin I use, the versions are populated in `$output` but `read` will hang.

I threw an echo on `$output` and a debug message after the `read` call. "here" is never printed
```bash
  echo "$output"
  IFS=' ' read -r -a versions_list <<<"$output"
  echo "here"
```

```
$ /opt/homebrew/opt/asdf/libexec/bin/asdf list all erlang
R13B03 R13B04 R14A R14B R14B01 R14B02 R14B03 R14B04 R15A R15B R15B01 R15B02 R15B03 R15B03-1 R16A_RELEASE_CANDIDATE R16B R16B01 R16B01_RC1 R16B02 R16B03 R16B03-1 R16B03_yielding_binary_to_term 17.0-rc1 17.0-rc2 17.0 17.0.1 17.0.2 17.1 17.1.1 17.1.2 17.2 17.2.1 17.2.2 17.3 17.3.1 17.3.2 17.3.3 17.3.4 17.4 17.4.1 17.5 17.5.1 17.5.2 17.5.3 17.5.4 17.5.5 17.5.6 17.5.6.1 17.5.6.2 17.5.6.3 17.5.6.4 17.5.6.5 17.5.6.6 17.5.6.7 17.5.6.8 17.5.6.9 17.5.6.10 18.0-rc1 18.0-rc2 18.0 18.0.1 18.0.2 18.0.3 18.1 18.1.1 18.1.2 18.1.3 18.1.4 18.1.5 18.2 18.2.1 18.2.2 18.2.3 18.2.4.0.1 18.2.4 18.2.4.1 18.3 18.3.1 18.3.2 18.3.3 18.3.4 18.3.4.1 18.3.4.1.1 18.3.4.2 18.3.4.3 18.3.4.4 18.3.4.5 18.3.4.6 18.3.4.7 18.3.4.8 18.3.4.9 18.3.4.10 18.3.4.11 19.0-rc1 19.0-rc2 19.0 19.0.1 19.0.2 19.0.3 19.0.4 19.0.5 19.0.6 19.0.7 19.1 19.1.1 19.1.2 19.1.3 19.1.4 19.1.5 19.1.6 19.1.6.1 19.2 19.2.1 19.2.2 19.2.3 19.2.3.1 19.3 19.3.1 19.3.2 19.3.3 19.3.4 19.3.5 19.3.6 19.3.6.1 19.3.6.2 19.3.6.3 19.3.6.4 19.3.6.5 19.3.6.6 19.3.6.7 19.3.6.8 19.3.6.9 19.3.6.10 19.3.6.11 19.3.6.12 19.3.6.13 20.0-rc1 20.0-rc2 20.0 20.0.1 20.0.2 20.0.3 20.0.4 20.0.5 20.1 20.1.1 20.1.2 20.1.3 20.1.4 20.1.5 20.1.6 20.1.7 20.1.7.1 20.2.0.1 20.2 20.2.1 20.2.2 20.2.3 20.2.4 20.3 20.3.1 20.3.2 20.3.2.1 20.3.3 20.3.4 20.3.5 20.3.6 20.3.7 20.3.8 20.3.8.1 20.3.8.2 20.3.8.3 20.3.8.4 20.3.8.5 20.3.8.6 20.3.8.7 20.3.8.8 20.3.8.9 20.3.8.10 20.3.8.11 20.3.8.12 20.3.8.13 20.3.8.14 20.3.8.15 20.3.8.16 20.3.8.17 20.3.8.18 20.3.8.19 20.3.8.20 20.3.8.21 20.3.8.22 20.3.8.23 20.3.8.24 20.3.8.25 20.3.8.26 21.0-rc1 21.0-rc2 21.0 21.0.1 21.0.2 21.0.3 21.0.4 21.0.5 21.0.6 21.0.7 21.0.8 21.0.9 21.1 21.1.1 21.1.2 21.1.3 21.1.4 21.2 21.2.1 21.2.2 21.2.3 21.2.4 21.2.5 21.2.6 21.2.7 21.3 21.3.1 21.3.2 21.3.3 21.3.4 21.3.5 21.3.6 21.3.7 21.3.7.1 21.3.8 21.3.8.1 21.3.8.2 21.3.8.3 21.3.8.4 21.3.8.5 21.3.8.6 21.3.8.7 21.3.8.8 21.3.8.9 21.3.8.10 21.3.8.11 21.3.8.12 21.3.8.13 21.3.8.14 21.3.8.15 21.3.8.16 21.3.8.17 21.3.8.18 21.3.8.19 21.3.8.20 21.3.8.21 21.3.8.22 21.3.8.23 21.3.8.24 22.0-rc1 22.0-rc2 22.0-rc3 22.0 22.0.1 22.0.2 22.0.3 22.0.4 22.0.5 22.0.6 22.0.7 22.1 22.1.1 22.1.2 22.1.3 22.1.4 22.1.5 22.1.6 22.1.7 22.1.8 22.1.8.1 22.2 22.2.1 22.2.2 22.2.3 22.2.4 22.2.5 22.2.6 22.2.7 22.2.8 22.3 22.3.1 22.3.2 22.3.3 22.3.4 22.3.4.1 22.3.4.2 22.3.4.3 22.3.4.4 22.3.4.5 22.3.4.6 22.3.4.7 22.3.4.8 22.3.4.9 22.3.4.10 22.3.4.11 22.3.4.12 22.3.4.12.1 22.3.4.13 22.3.4.14 22.3.4.15 22.3.4.16 22.3.4.17 22.3.4.18 22.3.4.19 22.3.4.20 22.3.4.21 22.3.4.22 22.3.4.23 22.3.4.24 22.3.4.25 22.3.4.26 23.0-rc1 23.0-rc2 23.0-rc3 23.0 23.0.1 23.0.2 23.0.3 23.0.4 23.1 23.1.1 23.1.2 23.1.3 23.1.4 23.1.4.1 23.1.5 23.2 23.2.1 23.2.2 23.2.3 23.2.4 23.2.5 23.2.6 23.2.7 23.2.7.1 23.2.7.2 23.2.7.3 23.2.7.4 23.2.7.5 23.3 23.3.1 23.3.2 23.3.3 23.3.4 23.3.4.1 23.3.4.2 23.3.4.3 23.3.4.4 23.3.4.5 23.3.4.6 23.3.4.7 23.3.4.8 23.3.4.9 23.3.4.10 23.3.4.11 23.3.4.12 23.3.4.13 23.3.4.14 23.3.4.15 24.0-rc1 24.0-rc2 24.0-rc3 24.0 24.0.1 24.0.2 24.0.3 24.0.4 24.0.5 24.0.6 24.1 24.1.1 24.1.2 24.1.3 24.1.4 24.1.5 24.1.6 24.1.7 24.2 24.2.1 24.2.2 24.3 24.3.1 24.3.2 24.3.3 24.3.4 24.3.4.1 24.3.4.2 25.0-rc1 25.0-rc2 25.0-rc3 25.0 25.0.1 25.0.2
^C
```

```
$ /opt/homebrew/opt/asdf/libexec/bin/asdf list all ruby
1.8.5-p52 1.8.5-p113 1.8.5-p114 1.8.5-p115 1.8.5-p231 1.8.6 1.8.6-p36 1.8.6-p110 1.8.6-p111 1.8.6-p114 1.8.6-p230 1.8.6-p286 1.8.6-p287 1.8.6-p368 1.8.6-p369 1.8.6-p383 1.8.6-p388 1.8.6-p398 1.8.6-p399 1.8.6-p420 1.8.7-preview1 1.8.7-preview2 1.8.7-preview3 1.8.7-preview4 1.8.7 1.8.7-p17 1.8.7-p22 1.8.7-p71 1.8.7-p72 1.8.7-p160 1.8.7-p173 1.8.7-p174 1.8.7-p248 1.8.7-p249 1.8.7-p299 1.8.7-p301 1.8.7-p302 1.8.7-p330 1.8.7-p334 1.8.7-p352 1.8.7-p357 1.8.7-p358 1.8.7-p370 1.8.7-p371 1.8.7-p373 1.8.7-p374 1.8.7-p375 1.9.0-0 1.9.0-1 1.9.0-2 1.9.0-3 1.9.0-4 1.9.0-5 1.9.1-preview1 1.9.1-preview2 1.9.1-rc1 1.9.1-rc2 1.9.1-p0 1.9.1-p129 1.9.1-p243 1.9.1-p376 1.9.1-p378 1.9.1-p429 1.9.1-p430 1.9.1-p431 1.9.2-preview1 1.9.2-preview3 1.9.2-rc1 1.9.2-rc2 1.9.2-p0 1.9.2-p136 1.9.2-p180 1.9.2-p290 1.9.2-p318 1.9.2-p320 1.9.2-p326 1.9.2-p330 1.9.3-dev 1.9.3-preview1 1.9.3-rc1 1.9.3-p0 1.9.3-p105 1.9.3-p125 1.9.3-p194 1.9.3-p286 1.9.3-p327 1.9.3-p362 1.9.3-p374 1.9.3-p385 1.9.3-p392 1.9.3-p426 1.9.3-p429 1.9.3-p448 1.9.3-p484 1.9.3-p545 1.9.3-p547 1.9.3-p550 1.9.3-p551 2.0.0-dev 2.0.0-preview1 2.0.0-preview2 2.0.0-rc1 2.0.0-rc2 2.0.0-p0 2.0.0-p195 2.0.0-p247 2.0.0-p353 2.0.0-p451 2.0.0-p481 2.0.0-p576 2.0.0-p594 2.0.0-p598 2.0.0-p643 2.0.0-p645 2.0.0-p647 2.0.0-p648 2.1.0-dev 2.1.0-preview1 2.1.0-preview2 2.1.0-rc1 2.1.0 2.1.1 2.1.2 2.1.3 2.1.4 2.1.5 2.1.6 2.1.7 2.1.8 2.1.9 2.1.10 2.2.0-dev 2.2.0-preview1 2.2.0-preview2 2.2.0-rc1 2.2.0 2.2.1 2.2.2 2.2.3 2.2.4 2.2.5 2.2.6 2.2.7 2.2.8 2.2.9 2.2.10 2.3.0-dev 2.3.0-preview1 2.3.0-preview2 2.3.0 2.3.1 2.3.2 2.3.3 2.3.4 2.3.5 2.3.6 2.3.7 2.3.8 2.4.0-dev 2.4.0-preview1 2.4.0-preview2 2.4.0-preview3 2.4.0-rc1 2.4.0 2.4.1 2.4.2 2.4.3 2.4.4 2.4.5 2.4.6 2.4.7 2.4.8 2.4.9 2.4.10 2.5.0-dev 2.5.0-preview1 2.5.0-rc1 2.5.0 2.5.1 2.5.2 2.5.3 2.5.4 2.5.5 2.5.6 2.5.7 2.5.8 2.5.9 2.6.0-dev 2.6.0-preview1 2.6.0-preview2 2.6.0-preview3 2.6.0-rc1 2.6.0-rc2 2.6.0 2.6.1 2.6.2 2.6.3 2.6.4 2.6.5 2.6.6 2.6.7 2.6.8 2.6.9 2.6.10 2.7.0-dev 2.7.0-preview1 2.7.0-preview2 2.7.0-preview3 2.7.0-rc1 2.7.0-rc2 2.7.0 2.7.1 2.7.2 2.7.3 2.7.4 2.7.5 2.7.6 3.0.0-dev 3.0.0-preview1 3.0.0-preview2 3.0.0-rc1 3.0.0 3.0.1 3.0.2 3.0.3 3.0.4 3.1.0-dev 3.1.0-preview1 3.1.0 3.1.1 3.1.2 3.2.0-dev 3.2.0-preview1 artichoke-dev jruby-dev jruby-1.5.6 jruby-1.6.3 jruby-1.6.4 jruby-1.6.5 jruby-1.6.5.1 jruby-1.6.6 jruby-1.6.7 jruby-1.6.7.2 jruby-1.6.8 jruby-1.7.0-preview1 jruby-1.7.0-preview2 jruby-1.7.0-rc1 jruby-1.7.0-rc2 jruby-1.7.0 jruby-1.7.1 jruby-1.7.2 jruby-1.7.3 jruby-1.7.4 jruby-1.7.5 jruby-1.7.6 jruby-1.7.7 jruby-1.7.8 jruby-1.7.9 jruby-1.7.10 jruby-1.7.11 jruby-1.7.12 jruby-1.7.13 jruby-1.7.14 jruby-1.7.15 jruby-1.7.16 jruby-1.7.16.1 jruby-1.7.16.2 jruby-1.7.17 jruby-1.7.18 jruby-1.7.19 jruby-1.7.20 jruby-1.7.20.1 jruby-1.7.21 jruby-1.7.22 jruby-1.7.23 jruby-1.7.24 jruby-1.7.25 jruby-1.7.26 jruby-1.7.27 jruby-9.0.0.0.pre1 jruby-9.0.0.0.pre2 jruby-9.0.0.0.rc1 jruby-9.0.0.0.rc2 jruby-9.0.0.0 jruby-9.0.1.0 jruby-9.0.3.0 jruby-9.0.4.0 jruby-9.0.5.0 jruby-9.1.0.0-dev jruby-9.1.0.0 jruby-9.1.1.0 jruby-9.1.2.0 jruby-9.1.3.0 jruby-9.1.4.0 jruby-9.1.5.0 jruby-9.1.6.0 jruby-9.1.7.0 jruby-9.1.8.0 jruby-9.1.9.0 jruby-9.1.10.0 jruby-9.1.11.0 jruby-9.1.12.0 jruby-9.1.13.0 jruby-9.1.14.0 jruby-9.1.15.0 jruby-9.1.16.0 jruby-9.1.17.0 jruby-9.2.0.0-dev jruby-9.2.0.0 jruby-9.2.1.0-dev jruby-9.2.1.0 jruby-9.2.3.0 jruby-9.2.4.0 jruby-9.2.4.1 jruby-9.2.5.0 jruby-9.2.6.0 jruby-9.2.7.0 jruby-9.2.8.0 jruby-9.2.9.0 jruby-9.2.10.0 jruby-9.2.11.0 jruby-9.2.11.1 jruby-9.2.12.0 jruby-9.2.13.0 jruby-9.2.14.0 jruby-9.2.15.0 jruby-9.2.16.0 jruby-9.2.17.0 jruby-9.2.18.0 jruby-9.2.19.0 jruby-9.2.20.0 jruby-9.2.20.1 jruby-9.3.0.0 jruby-9.3.1.0 jruby-9.3.2.0 jruby-9.3.3.0 jruby-9.3.4.0 maglev-1.0.0 maglev-1.1.0-dev maglev-2.0.0-dev mruby-dev mruby-1.0.0 mruby-1.1.0 mruby-1.2.0 mruby-1.3.0 mruby-1.4.0 mruby-1.4.1 mruby-2.0.0 mruby-2.0.1 mruby-2.1.0 mruby-2.1.1 mruby-2.1.2 mruby-3.0.0 rbx-2.2.2 rbx-2.2.3 rbx-2.2.4 rbx-2.2.5 rbx-2.2.6 rbx-2.2.7 rbx-2.2.8 rbx-2.2.9 rbx-2.2.10 rbx-2.3.0 rbx-2.4.0 rbx-2.4.1 rbx-2.5.0 rbx-2.5.1 rbx-2.5.2 rbx-2.5.3 rbx-2.5.4 rbx-2.5.5 rbx-2.5.6 rbx-2.5.7 rbx-2.5.8 rbx-2.6 rbx-2.7 rbx-2.8 rbx-2.9 rbx-2.10 rbx-2.11 rbx-2.71828182 rbx-3.0 rbx-3.1 rbx-3.2 rbx-3.3 rbx-3.4 rbx-3.5 rbx-3.6 rbx-3.7 rbx-3.8 rbx-3.9 rbx-3.10 rbx-3.11 rbx-3.12 rbx-3.13 rbx-3.14 rbx-3.15 rbx-3.16 rbx-3.17 rbx-3.18 rbx-3.19 rbx-3.20 rbx-3.21 rbx-3.22 rbx-3.23 rbx-3.24 rbx-3.25 rbx-3.26 rbx-3.27 rbx-3.28 rbx-3.29 rbx-3.30 rbx-3.31 rbx-3.32 rbx-3.33 rbx-3.34 rbx-3.35 rbx-3.36 rbx-3.37 rbx-3.38 rbx-3.39 rbx-3.40 rbx-3.41 rbx-3.42 rbx-3.43 rbx-3.44 rbx-3.45 rbx-3.46 rbx-3.47 rbx-3.48 rbx-3.49 rbx-3.50 rbx-3.51 rbx-3.52 rbx-3.53 rbx-3.54 rbx-3.55 rbx-3.56 rbx-3.57 rbx-3.58 rbx-3.59 rbx-3.60 rbx-3.61 rbx-3.62 rbx-3.63 rbx-3.64 rbx-3.65 rbx-3.66 rbx-3.67 rbx-3.68 rbx-3.69 rbx-3.70 rbx-3.71 rbx-3.72 rbx-3.73 rbx-3.74 rbx-3.75 rbx-3.76 rbx-3.77 rbx-3.78 rbx-3.79 rbx-3.80 rbx-3.81 rbx-3.82 rbx-3.83 rbx-3.84 rbx-3.85 rbx-3.86 rbx-3.87 rbx-3.88 rbx-3.89 rbx-3.90 rbx-3.91 rbx-3.92 rbx-3.93 rbx-3.94 rbx-3.95 rbx-3.96 rbx-3.97 rbx-3.98 rbx-3.99 rbx-3.100 rbx-3.101 rbx-3.102 rbx-3.103 rbx-3.104 rbx-3.105 rbx-3.106 rbx-3.107 rbx-4.0 rbx-4.1 rbx-4.2 rbx-4.3 rbx-4.4 rbx-4.5 rbx-4.6 rbx-4.7 rbx-4.8 rbx-4.9 rbx-4.10 rbx-4.11 rbx-4.12 rbx-4.13 rbx-4.14 rbx-4.15 rbx-4.16 rbx-4.18 rbx-4.19 rbx-4.20 rbx-5.0 ree-1.8.7-2011.03 ree-1.8.7-2011.12 ree-1.8.7-2012.01 ree-1.8.7-2012.02 truffleruby-dev truffleruby-1.0.0-rc10 truffleruby-1.0.0-rc11 truffleruby-1.0.0-rc12 truffleruby-1.0.0-rc13 truffleruby-1.0.0-rc14 truffleruby-1.0.0-rc15 truffleruby-1.0.0-rc16 truffleruby-1.0.0-rc2 truffleruby-1.0.0-rc3 truffleruby-1.0.0-rc5 truffleruby-1.0.0-rc6 truffleruby-1.0.0-rc7 truffleruby-1.0.0-rc8 truffleruby-1.0.0-rc9 truffleruby-19.0.0 truffleruby-19.1.0 truffleruby-19.2.0 truffleruby-19.2.0.1 truffleruby-19.3.0 truffleruby-19.3.0.2 truffleruby-19.3.1 truffleruby-20.0.0 truffleruby-20.1.0 truffleruby-20.2.0 truffleruby-20.3.0 truffleruby-21.0.0 truffleruby-21.1.0 truffleruby-21.2.0 truffleruby-21.2.0.1 truffleruby-21.3.0 truffleruby-22.0.0.2 truffleruby-22.1.0 truffleruby+graalvm-dev truffleruby+graalvm-20.1.0 truffleruby+graalvm-20.2.0 truffleruby+graalvm-20.3.0 truffleruby+graalvm-21.0.0 truffleruby+graalvm-21.1.0 truffleruby+graalvm-21.2.0 truffleruby+graalvm-21.3.0 truffleruby+graalvm-22.0.0.2 truffleruby+graalvm-22.1.0
^C
```

I suspect `$output` somehow isn't terminated properly? (no newline / EOL)
