### ISSUE TITLE
bug: Updating asdf did not update version number in shim paths

### ISSUE THREAD

**Issue by AndrewRayCode** [asdf-vm/asdf#1147] opened 2022-01-03 20:21 UTC
### Describe the Bug

After updating asdf from 0.8.1.1 to 0.9.0, in my ~/.asdf/shims folder, I have lots of shims pointing to the older version:

```
~/.asdf/shims $ rg 0.8.1

python
6:exec /usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf exec "python" "$@"

pip3
6:exec /usr/local/Cellar/asdf/0.8.1_1/libexec/bin/asdf exec "pip3" "$@"
```

etc

### Steps to Reproduce

Install asdf with homebrew

Update asdf with homebrew

### Expected Behaviour

Shims to be updated

### Actual Behaviour

Shims point to nonexistent older asdf version

### Environment

```shell
$ asdf info
OS:
Darwin andrew.ray-pro 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

SHELL:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.

ASDF VERSION:
v0.9.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/Cellar/asdf/0.9.0/libexec

ASDF INSTALLED PLUGINS:
python                       git@github.com:danhper/asdf-python.git master 57a4d72
ruby                         git@github.com:asdf-vm/asdf-ruby.git master d0e5a20
terraform                    git@github.com:Banno/asdf-hashicorp.git master 307f78c
```

**Comment by baens** [comment] 2022-01-05 03:45
I'm having the same issue and `asdf reshim` doesn't seem to fix the problem

**Comment by baens** [comment] 2022-01-05 03:48
A small workaround is to remove the plugin, then install it again.

**Comment by slehman** [comment] 2022-01-05 20:51
Ran into the same issue. My workaround was to rename the `~/.asdf/shims` directory and run `asdf reshim`. That forces `asdf` to recreate the `shims` directory and regenerate all of the shims using the updated envvar for `ASDF_DIR`.

**Comment by alecho** [comment] 2022-01-07 17:38
> Ran into the same issue. My workaround was to rename the `~/.asdf/shims` directory and run `asdf reshim`. That forces `asdf` to recreate the `shims` directory and regenerate all of the shims using the updated envvar for `ASDF_DIR`.

Confirming removing the directory and reshimming worked for me as well.

**Comment by duderman** [comment] 2022-01-27 17:42
same here

**Comment by jasonwc** [comment] 2022-01-28 00:27
Another grateful developer here. Moving the dirs and reshimming worked for me.

**Comment by jnishina** [comment] 2022-02-04 16:23
^^ thank you @slehman

**Comment by Johnsalzarulo** [comment] 2022-02-25 14:30
+1  Moving the shims dir and asdf reshim worked

**Comment by jfly** [comment] 2022-04-08 17:06
I think we should close this issue. AFAICT, this is a dupe of https://github.com/asdf-vm/asdf/issues/1103. I tried to write up a very detailed explanation of things over on https://github.com/asdf-vm/asdf/issues/1103#issuecomment-1093094933.

**Comment by nitrocode** [comment] 2022-06-30 03:52
I installed asdf using homebrew. Can we update the formula so the asdf directory is recreated and `asdf shim` when a new version is installed?

Or is there a way we can automate this somehow within asdf?

**Comment by jthegedus** [comment] 2022-06-30 04:46
> I think we should close this issue. AFAICT, this is a dupe of #1103. I tried to write up a very detailed explanation of things over on [#1103 (comment)](https://github.com/asdf-vm/asdf/issues/1103#issuecomment-1093094933).

Taking this advice and closing this in favour of #1103

**Closed by jthegedus** 2022-06-30 04:46 UTC
Labels: bug
