### ISSUE TITLE
bug: Tool version from .tool-versions has trailing whitespace.

### ISSUE THREAD

**Issue by tobiase** [asdf-vm/asdf#1234] opened 2022-05-22 01:36 UTC
### Describe the Bug

Two spaces are appended to the versions read from `.tool-versions` which leads to the buildfile not being findable
and thus the tool not being installed.

### Steps to Reproduce

1. Create `.tool-versions` file
```
python 3.9.2
```
2. Run `asdf install`

### Expected Behaviour

The tool should be installed with the version specified in the `.tool-versions` file.

### Actual Behaviour

E.g. I have a project with a `.tool-versions` file that contains only `python 3.9.2`.
After running `asdf install` in the project dir I see "python-build: definition not found: 3.9.2"
and the tool is not installed.

I tried debugging the problem and figured out that in https://github.com/asdf-vm/asdf/blob/f8109e0d8c211156c1725eb788541dff6e408610/lib/functions/installs.bash#L56 `$plugin_version` has two trailing spaces.
I was able to discover that by inserting `echo "$(echo -e "${plugin_versions}" | tr '[:space:]' 'x')"` above L.56 that replaces any whitespace in `$plugin_version` with `x`. The console output was `3.9.2xx`

### Environment

```shell
➜  xyz git:(master) ✗ asdf info
OS:
Linux DESKTOP-E4BQH84 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-ubuntu-linux-gnu)

ASDF VERSION:
v0.10.1-f8109e0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/tobias/.asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git master ce9d3c6
python                       https://github.com/danhper/asdf-python.git master 57ef777
```

### asdf plugins affected (if relevant)

nodejs, python, postgres

**Comment by Stratus3D** [comment] 2022-05-25 20:16
@tobiase I am unable to replicate this on my machine (see below). I've also not seen reports of similar bugs. 

```
$ asdf install
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 253 (delta 134), reused 163 (delta 129), pack-reused 79
Receiving objects: 100% (253/253), 80.43 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (154/154), completed with 32 local objects.
From https://github.com/pyenv/pyenv
   6d20b3b1..0930533d  master     -> origin/master
 * [new tag]           v2.3.0     -> v2.3.0
python-build 3.9.2 /Users/~/.asdf/installs/python/3.9.2
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.9.2.tar.xz...
-> https://www.python.org/ftp/python/3.9.2/Python-3.9.2.tar.xz
Installing Python-3.9.2...
patching file Misc/NEWS.d/next/Build/2021-10-11-16-27-38.bpo-45405.iSfdW5.rst
patching file configure
patching file configure.ac
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.9.2 to /Users/~/.asdf/installs/python/3.9.2
```

Do you have any idea why trailing spaces were appended to your version number? Does this happen with all plugins or just the python one?

**Comment by tobiase** [comment] 2022-05-25 21:06
> Do you have any idea why trailing spaces were appended to your version number?

No. I doublechecked and the `.tool-versions` file doesn't contain the trailing whitespace.
I'm able to install specific versions from the command line without problems.
The issue only shows with the  `.tool-versions` file.

> Does this happen with all plugins

Yes.

**Comment by Stratus3D** [comment] 2022-05-26 16:04
I'm going to need someone else to validate this bug as I don't use `WSL2`. Alternatively if you can find where exactly the spaces are introduced I may be able to come up with fix based on that info.

**Comment by Stratus3D** [comment] 2022-05-26 19:29
No worries, thanks for putting together such a detailed ticket! Unfortunately this is one of those things that might be caused by something environment so it's only going to be possible to fix it in an environment where we can reproduce the bug.

@asdf-vm/core anyone use WSL2?

**Comment by jthegedus** [comment] 2022-07-17 08:10
I believe this issue is caused by `CRLF` line endings instead of the expected `LF`. Seems to be a common issue with WSL users.

Related issues:

- #1187 
- #953 
- #1297 

Quoting my response from the other issues for those who might find themselves here - https://github.com/asdf-vm/asdf/issues/1187#issuecomment-1183388329

---

So two things to keep in mind when using WSL2 environment:

1. From our [FAQ](https://asdf-vm.com/learn-more/faq.html)
>Importantly, WSL2 is only expected to work properly when the current working directory is a Unix drive and not a bound Windows drive.

2. The error reported shows:
```
bash: /home/USER/.asdf/asdf.sh: line 9: syntax error near unexpected token `elif'
'ash: /home/USER/.asdf/asdf.sh: line 9: `  elif [[ "$_under" == *".sh" ]]; then
bash: /home/USER/.asdf/completions/asdf.bash: line 1: syntax error near unexpected token `$'{\r''
'ash: /home/USER/.asdf/completions/asdf.bash: line 1: `_asdf() {
```

The 3rd line here shows an unexpected token `\r` which is likely due to this repository being cloned to a non-Unix location or by using Git in a Windows environment. Changing your line endings to LF from CRLF might fix this.

---

Now OP didn't paste their complete error output, but given their find/replace produced an output with two trailing `x`s

>echo "$(echo -e "${plugin_versions}" | tr '[:space:]' 'x')"
>The console output was `3.9.2xx`

I am inclined to say that this was because of `CRLF`. With the other linked errors the issue was because `asdf` code has been cloned with `CRLF`, in this instance, just the `.tool-versions` file seems to have the issue hence when it is passed into the python build is when it errors and why the OPs experience is different from the listed related issues.

Closing this issue as OP has not reported this issue again and their proposed fix is for a scenario we don't want to mask with workarounds.

**Closed by jthegedus** 2022-07-17 08:10 UTC
Labels: bug

**Comment by tobiase** [comment] 2022-07-17 11:12
> I believe this issue is caused by CRLF line endings instead of the expected LF

I tested your assumption, and it is correct.
Changing the line endings in `.tool-versions` from `CRLF` to `LF` fixed the issue for me.
