### ISSUE TITLE
Project-Specific Virtual Environments?

### ISSUE THREAD

**Issue by geoffreywiseman** [asdf-vm/asdf#677] opened 2020-03-12 16:17 UTC
Trying to understand how `asdf` fits into a world where you're looking for project-specific virtual environments. With languages like Ruby and Python where dependencies are installed to a 'central' place, it's not uncommon to want to know that your installation process installs all the necessary dependencies, rather than relying on dependencies that may be already present.

With those kinds of languages, I would often want to know that each project has its own clean environment -- I don't just python 3.8.2, I want a clean python 3.8.2 environment that no other project shares, so that if I have two python projects, I don't have to worry about interactions between the dependencies of both.

Is ASDF not really intended to handle that use case? If not, maybe wouldn't hurt to mention that in the managing versions documentation; I'd even be ok with putting in a documentation PR, except I don't know what the stance of the asdf project *is* on project-specific environments.  Couldn't find other related issues, any obvious references in the documentation ...

**Comment by Stratus3D** [comment] 2020-04-09 13:35
Related to https://github.com/asdf-vm/asdf/issues/167

In short, no it's not currently intended to solve that problem.

**Comment by geoffreywiseman** [comment] 2020-04-09 15:59
Yes, definitely #167 is heavily related if not exactly the same thing.  Thanks, was useful to be able to read that thread.

**Comment by justinmayer** [comment] 2020-08-15 05:20
> Trying to understand how `asdf` fits into a world where you're looking for project-specific virtual environments.

`asdf` allows for multiple tool versions to be installed, which can then be used by other (non-`asdf`) environment managers that creates project-specific environments using those tool versions.

In case it might be helpful, I posted a [detailed guide on how to use `asdf` with Python virtual environments](https://github.com/asdf-vm/asdf/issues/636#issuecomment-674092994). Feel free to post a comment there if you have any questions about it.

@Stratus3D: Given that this is a duplicate of 167 and 636, I think this issue can be closed.

**Comment by HashNuke** [comment] 2020-10-07 03:34
@geoffreywiseman The package/library install path makes all the difference. `asdf` doesn't support different library install paths. Maybe this can be added in the future. But other tools like venv complement what asdf does and can be used together.

I don't have the full info you would require handy right now - but if you do need to play around, python has a way to set the path for "site packages" and this can be set per python project.

Closing this ticket for now. Please feel free to continue the discussion and reopen if appropriate.

**Closed by HashNuke** 2020-10-07 03:34 UTC
