### ISSUE TITLE
Shims not working when .tool-versions path contains spaces

### ISSUE THREAD

**Issue by endersstocker** [asdf-vm/asdf#202] opened 2017-06-24 10:54 UTC
If the `.tool-versions` file is present in a path that contains spaces and declares at least one versions, using a shim results in a series of `No such file or directory` grep errors and a failure to use the versions specified in that `.tool-versions` file.

Steps to reproduce (using the erlang plugin as an example):
1. Install asdf and asdf-erlang.
2. Create a directory with a space in the name. (If you really want to see the extent of this bug, give the directory a name with a star like `\*\ my\ directory`.)
3. Create `.tool-versions` in that directory with the entry `erlang 20.0`.
4. Run `erl` from that directory.

**Comment by Stratus3D** [comment] 2017-06-29 17:37
@endersstocker what version of asdf you are using?

**Comment by vic** [comment] 2017-06-30 03:47
Reproduced this with master, 

```
vic@katan ~/f* k this> cat .tool-versions
erlang 20.0
vic@katan ~/f* k this> pwd
/home/vic/f* k this
vic@katan ~/f* k this> asdf current erlang
grep: /home/vic/f* k this: Is a directory
grep: k: No such file or directory
grep: this/.tool-versions: No such file or directory
20.0 (set by /home/vic/.tool-versions)
```

**Comment by jonknapp** [comment] 2017-08-30 05:21
I have the same issue with `master` / ` v0.3.0-70-g29a29f1`.

**Comment by vic** [comment] 2017-09-04 01:47
Tested locally and looks like #224 fixes this, added  a test for it on e75cc3a

I'm closing this issue now.

**Comment by CrshOverride** [comment] 2017-09-15 16:28
It looks like this is also broken when using a legacy version file but this fix only addressed the tool-version path. Can we re-open so I can submit a PR against this issue rather than opening a new one?

**Comment by Stratus3D** [comment] 2017-09-15 17:23
I don't have to check this right now, but if that's the case yes we should. We should also write a test for the behavior so we don't have to deal with regressions.

**Closed** 2017-10-03 01:01 UTC
Labels: bug
