### ISSUE TITLE
Switch to the latest release of a version

### ISSUE THREAD

**Issue by turboninh** [asdf-vm/asdf#1342] opened 2022-10-06 08:32 UTC
### Is your feature request related to a problem? Please describe

Is there a way to automatically switch to another runtime version using only the major version. Using NodeJs plugin, for example, running `asdf local nodejs 16` doesn't work but `asdf local nodejs 16.17.0`.

### Describe the proposed solution

Implement `asdf local nodejs 16.x.x` or `asdf local nodejs 16.x` as a command, then allow `16.x` or `16.3.x` in **.tool-versions**

### Describe similar `asdf` features and why they are not sufficient

The command `asdf local nodejs 16.17.0` will create **.tool-versions** file in the project repo with `nodejs 16.17.0` in it, which does not take effect if the other team member clones the repo and have `16.17.1` installed locally.

### Describe other workarounds you've considered

Force other team member to install the same version

**Comment by jthegedus** [comment] 2022-12-30 12:29
You can get the very latest with `asdf local nodejs latest`.

Unfortunately, there seems to be a bug where the filter expression `asdf local nodejs latest 16` does not resolve as expected. `16` does not get passed to the `latest` function to filter properly.

**Comment by jthegedus** [comment] 2022-12-30 12:31
The feature request for:

>Implement asdf local nodejs 16.x.x or asdf local nodejs 16.x as a command, then allow 16.x or 16.3.x in .tool-versions

has already been discussed and declined numerous times.

If `asdf local nodejs latest` is not sufficient, then this issue can be closed as a duplicate.

**Comment by turboninh** [comment] 2023-01-01 18:00
The issue is more about better suppport for auto-switching between versions using **.tool-versions** file. With `nvm`, for example, I can create an `nvmrc` and put in `16` and it will automatically select 16.x on computers of my team members, `asdf` doesn't seem to support that.

**Comment by jthegedus** [comment] 2023-01-02 00:09
> The issue is more about better suppport for auto-switching between versions using **.tool-versions** file. With `nvm`, for example, I can create an `nvmrc` and put in `16` and it will automatically select 16.x on computers of my team members, `asdf` doesn't seem to support that.

Yes, that scenario is specifically not supported. `asdf` is designed to ensure everyone on a team is using the **exact** same version. If I am using `nodejs@16.0.0` and you are using `nodejs@16.19.0` those two versions are not anywhere close to being the same. They have different V8 engines, many different features and numerous bug fixes etc. How can we determine the root cause with this variability? Solution, remove the variability. Yes, this makes `asdf` slightly less convenient to use, but the purpose of locking a team to a version is to lock them to a version. Version ranges introduce variability.

Given we have discussed this particular feature request numerous times before, I will close this Issue as we are explicitly not going to support this feature.

**Closed by jthegedus** 2023-01-02 00:09 UTC
Labels: enhancement
