### ISSUE TITLE
bug:  Nodejs global package need to reinstall on every update

### ISSUE THREAD

**Issue by ookangzheng** [asdf-vm/asdf#1245] opened 2022-06-12 03:59 UTC
### Describe the Bug

On Mac 12.4, After I update NodeJS to the latest version, I ran `asdf global nodejs latest` and `asdf reshim nodejs` then restart terminal.

I try to execute some package that installed globally, and always throw this error.

```
wrangler
No preset version installed for command wrangler
Please install a version by running one of the following:

asdf install nodejs 18.3.0

or add one of the following versions in your config file at /Users/loll/.asdf/shims/.tool-versions
nodejs lts
```

My `~/.tool-versions`

```
❯ cat .tool-versions
golang 1.18.3
nodejs 18.3.0
python 3.10.4
terraform 1.2.2
```

To fix this problem, I have to reinstall `npm i -g wrangler` again to workaround.

Thanks

### Steps to Reproduce

1. asdf install nodejs latest
2. asdf global nodejs latest
3. asdf reshim nodejs
4. restart terminal

### Expected Behaviour

❯ wrangler -v
2.0.9

### Actual Behaviour

❯ wrangler
No preset version installed for command wrangler
Please install a version by running one of the following:

asdf install nodejs 18.3.0

or add one of the following versions in your config file at /Users/loll/.asdf/shims/.tool-versions
nodejs lts

### Environment

```shell
❯ asdf info
OS:
Darwin H7MLWQ16M5 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

SHELL:
zsh 5.8.1 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.10.2-7e7a1fa

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/loll/.asdf

ASDF INSTALLED PLUGINS:
golang                       https://github.com/kennyp/asdf-golang.git master 71424d8
helm                         https://github.com/Antiarchitect/asdf-helm.git master 87eef5a
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master ad4c3a7
pulumi                       https://github.com/canha/asdf-pulumi.git master 3e56e8e
python                       https://github.com/danhper/asdf-python.git master 57a4d72
terraform                    https://github.com/Banno/asdf-hashicorp.git master 3bc5829
```

**Comment by rektide** [comment] 2022-06-23 16:08
We face a similar issue here. We have a variety of programs we'd like to be available generally- `pino-pretty`, `nodemon`.

We find that we have to ongoingly keep calling `npm install -g` again and again, as different projects- some of which we don't even control- use different `.tool-versions`. It's frustrating for our developers to keep hitting this & having to `npm install -g` again. As we don't control a number of these repos, so we can't all agree to pick a single version for global installs and add that as an additional local `.tool-versions` to each of these projects, which is what the error text suggests.

It'd be very nice if we had a way to create truly global installs, that could always use a fixed nodejs version. Or some other solution.

**Comment by jthegedus** [comment] 2022-06-24 01:22
This isn't considered a bug in `asdf`. Tools installed by an `asdf`-managed tool are only tracked per version. We have no way in the `asdf` core to know if one tool or another installed by the `asdf`-managed tool should persist across versions, we would have to integrate with whichever tool you used to install the tool, this is a plugins domain.

Some plugins allow you to specify a list of actions to take post-install of a new version of the `asdf`-managed tool, allowing you to install "global" tools with the `asdf`-managed tool. [`asdf-nodejs`](https://github.com/asdf-vm/asdf-nodejs) is one such plugin. They call it [default npm packages](https://github.com/asdf-vm/asdf-nodejs#default-npm-packages). This is a list of `npm` packages that are installed with `npm i -g [<package>]` on each version install. This is list is global to your system and not associated with each project, so not very sharable across teams.

If an alternate solution exists to this problem, it would likely be implemented by the plugins anyway and not the core.

I am going to close this issue as it is not a bug and there is a way to do this with `asdf-nodejs`. If a discussion on alternate solutions is wanted, please open another issues as a feature request and discuss the behaviour you want with proposals for how `asdf` could solve this.

**Closed by jthegedus** 2022-06-24 01:22 UTC
Labels: bug
