### ISSUE TITLE
Cannot Use dbt with .asdf python packages

### ISSUE THREAD

**Issue by DragonEnergy** [asdf-vm/asdf#1243] opened 2022-06-08 00:28 UTC
### Describe the Bug

Currently trying to install https://docs.getdbt.com/dbt-cli/install/pip

after install I run ```dbt --version```

Followed by saying the bz2 module is not found 

### Steps to Reproduce

install dbt

run $ dbt --version

### Expected Behaviour

Output of the current version of dbt

### Actual Behaviour

Error after running

```dbt --version```

ile "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/task/build.py", line 1, in <module>
    from .run import RunTask, ModelRunner as run_model_runner
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/task/run.py", line 8, in <module>
    from .compile import CompileRunner, CompileTask
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/task/compile.py", line 3, in <module>
    from .runnable import GraphRunnableTask
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/task/runnable.py", line 17, in <module>
    from dbt.task.base import ConfiguredTask
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/task/base.py", line 47, in <module>
    from dbt.adapters.factory import register_adapter
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/adapters/factory.py", line 14, in <module>
    from dbt.adapters.protocol import (
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/adapters/protocol.py", line 27, in <module>
    from dbt.graph import Graph
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/graph/__init__.py", line 1, in <module>
    from .selector_spec import (  # noqa: F401
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/graph/selector_spec.py", line 8, in <module>
    from .graph import UniqueId
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/dbt/graph/graph.py", line 3, in <module>
    import networkx as nx  # type: ignore
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/networkx/__init__.py", line 59, in <module>
    from networkx import utils
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/networkx/utils/__init__.py", line 2, in <module>
    from networkx.utils.decorators import *
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/networkx/utils/decorators.py", line 11, in <module>
    import re, gzip, bz2
  File "/home/andres/.asdf/installs/python/3.10.4/lib/python3.10/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

### Environment

```shell
inux LAPTOP-S5TPKH13 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.9.0-9ee24a3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/andres/.asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
php                          https://github.com/asdf-community/asdf-php.git master ab86d61
python                       https://github.com/danhper/asdf-python.git master 57ef777
rust                         https://github.com/code-lever/asdf-rust.git master 0c88f99
```

**Comment by DragonEnergy** [comment] 2022-06-14 19:03
![image](https://user-images.githubusercontent.com/40496534/173668609-d14f22f4-3b00-43f2-acd5-9930e0f8121d.png)
Found this, still unsure what to do though

**Comment by jthegedus** [comment] 2022-06-16 15:54
Could this be a duplicate of https://github.com/asdf-vm/asdf/issues/570?

**Comment by jthegedus** [comment] 2022-06-24 01:45
I can gather 2 pieces of information from your initial error:
1. `dbt` is resolving to an `asdf` version of `python`. This is good.
2. the Python lib `bz2.py` is expecting a module named `_bz2` but couldn't find it.

Point 2 sounds like a missing system dependency. `asdf` doesn't manage dependencies, you have to follow instructions from the **plugin repo** for dependencies.

A quick Google of point 2s error returns this [SO Q.&A](https://stackoverflow.com/a/12806325/7911479). The result of which is you need a new system dependency `libbz2-dev`. This lib is mentioned in #570 and as stated there, is not an issue with `asdf`, but that a Python lib you are using requires a system dependency you are missing.

I am closing this as the method to "install python normally" that "operate optimally" likely installs this system dependency for you that were not manually installed during the `asdf-python` install.

`asdf-python` uses [python-build](https://github.com/yyuu/pyenv/tree/master/plugins/python-build) which in turn is a [pyenv](https://github.com/pyenv/pyenv) plugin which [itself suggests installing common system libraries](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) Python libraries use. This pyenv list of tools is shared in #570.

**Closed by jthegedus** 2022-06-24 01:45 UTC
Labels: bug
