### ISSUE TITLE
with_shim_executable: command not found

### ISSUE THREAD

**Issue by DamianRivas** [asdf-vm/asdf#730] opened 2020-05-20 22:33 UTC
**Describe the bug**

I installed deno v1.0.0 using asdf and this plug-in: https://github.com/asdf-community/asdf-deno

I get an error when trying to run deno

**To Reproduce**

All I did was run this exact command in the terminal
```
deno
```

**Expected behavior**

The deno runtime should've run.

**Actual behavior**

I got this error
```
➜  Damian deno
/home/damianrivas/.asdf/lib/commands/command-exec.bash: line 31: with_shim_executable: command not found
➜  Damian
```

### Environment

**OS**: Ubuntu 18.04 in Windows Subsystem for Linux

**asdf version**: v0.7.8-4a3e3d6

**asdf plugins affected (if relevant)**:

**asdf plugins installed**:

https://github.com/asdf-community/asdf-deno

**Screenshots**

**Additional context**

I looked at the source file identified in the error and went from there. I discovered that `with_shim_executable` is a function written in `utils.bash` in the asdf source.

I use ZSH if that matters.

**Comment by jthegedus** [comment] 2020-05-21 06:36
I am unable to reproduce this with this setup:

`operating system`: `ubuntu 20.04`
`asdf --version`: `v0.7.8-d652835`
`asdf plugin list --refs | grep deno`: `deno master 3860217`

Can you please verify that this only happens for a single plugin?

**Comment by DamianRivas** [comment] 2020-05-23 22:59
It is the only plug-in I have installed. This is the first time I ever use asdf and `deno` is the first and only software I installed with it

**Comment by jthegedus** [comment] 2020-05-24 00:00
@DamianRivas Can you install another plugin, say `nodejs` and see if you get the same result. It will help us narrow down whether it is an error in the plugin or in the asdf core.

**Comment by ryuheechul** [comment] 2020-07-26 11:23
In my case, this happened after `brew upgrade asdf` failed on macbook running with Big Sur.
Which I was able to fix the issue by https://github.com/Homebrew/brew/issues/7803#issuecomment-648601678 and reinstalling.

**Comment by jthegedus** [comment] 2020-08-19 10:39
@ryuheechul So is this issue still present, or was it specifically Homebrew and BigSur related?

**Comment by ryuheechul** [comment] 2020-08-20 07:59
@jthegedus I believe this macOS issue that can be dealt with by installing developer tools provided by Apple. However people could still be confused by the error when they first discover it, although I'm not sure what can be done in asdf's side.

**Comment by jthegedus** [comment] 2020-08-20 08:18
Right, Brew depends on a macOS developer tools - https://docs.brew.sh/Installation#macos-requirements

Homebrew never works as smoothly for me as it does others 🤷

@DamianRivas I'm tracking this change alongside other WSL issues in #465

**Comment by Stratus3D** [comment] 2021-12-03 15:40
@ryuheechul @DamianRivas can you test this on the latest version of asdf? `v0.9.0` was just released.

**Comment by DamianRivas** [comment] 2021-12-03 18:06
@Stratus3D It's been a while. I use zsh + oh-my-zsh and installed it the way I think the documentation intends for us to do so. I cloned the repo this way
```terminal
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0
```
And I added the [plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/asdf) to my .zshrc file: `plugins=(git asdf)`

But when I start a new terminal I see this:
```terminal
/home/damianrivas/.asdf/completions/asdf.bash:80: command not found: complete
```
`complete` is a bash builtin, there is no binary for it so that error makes sense given that I'm a zsh user. Still, not very user friendly. I feel like that is something that should work out of the box.

---

Anyway, that's just the autocomplete feature, but the `asdf` command itself works. And I'm happy to report that installing deno was quick, easy, and painless!

```terminal
➜  ~ asdf install deno latest
∗ Downloading and installing deno...
Archive:  /home/damianrivas/.asdf/installs/deno/1.16.3/bin/deno.zip
  inflating: /home/damianrivas/.asdf/installs/deno/1.16.3/bin/deno
The installation was successful!
➜  ~ asdf current
deno            ______          No version is set. Run "asdf <global|shell|local> deno <version>"
➜  ~ asdf global deno latest
➜  ~ cat ~/.tool-versions
deno 1.16.3
➜  ~ which deno
/home/damianrivas/.asdf/shims/deno
➜  ~ deno
Deno 1.16.3
exit using ctrl+d or close()
>
```

And yes, this was done in WSL.

I may give this tool a solid chance now, but I really don't like that message that pops up every time I start up a new terminal window.

**Comment by jthegedus** [comment] 2021-12-05 12:17
The OMZSH plugin for `asdf` uses the Bash completions not the ZSH completions. This particular issue `command not found: complete` has been covered a few times in this repo:

- #68
- #692

Recommendations are one of:

- use ZSH native completions with ZSH `compinit`
   ```
	# append completions to fpath 
	fpath=(${ASDF_DIR}/completions $fpath) 

	# initialise completions with ZSH's compinit 
	autoload -Uz compinit && compinit
	```
- run `bashcompinit `after you source the OMZSH bash-completion-based plugin
	```
	autoload -U +X bashcompinit && bashcompinit
	```

Unfortunately, automatically running `compinit`/`bashcompinit` in the completion script is not an option.

I am going to close this as a solution is known and the latest documentation walks the user through the setup process to avoid this with a warn of external plugins not being updated accordingly.

![image](https://user-images.githubusercontent.com/20798510/144746045-382533d5-7241-4623-a798-5efa1b00768f.png)
source - https://asdf-vm.com/guide/getting-started.html#_3-install-asdf

**Closed by jthegedus** 2021-12-05 12:17 UTC
Labels: bug
