### ISSUE TITLE
Installing a version of a library failed, now end up in purgatory

### ISSUE THREAD

**Issue by tomciopp** [asdf-vm/asdf#724] opened 2020-05-13 16:46 UTC
**Describe the bug**

It looks like there was a failure somewhere when installing the latest release of erlang. Whenever I try to use the version that was installed it tells me that it was not installed. If I try to uninstall the version it tells me that there is `No such version`. If I try to install it again I get `There's already a build named asdf_23.0`

**To Reproduce**

`asdf install erlang 23.0`

**Expected behavior**

It installs erlang version 23.0

**Actual behavior**

It says it installed it and it says it did not install it at the same time.

### Environment

**OS**: OSX 10.15.4

**asdf version**: v0.7.8

**asdf plugins affected (if relevant)**: erlang

**asdf plugins installed**: erlang,elixir

<img width="900" alt="asdf-lol-wut" src="https://user-images.githubusercontent.com/544875/81840950-b0219a00-9517-11ea-9041-02e17e2f8d7b.png">

**Comment by tomciopp** [comment] 2020-05-13 16:47
<img width="346" alt="Screen Shot 2020-05-13 at 12 47 14 PM" src="https://user-images.githubusercontent.com/544875/81841098-e6f7b000-9517-11ea-9871-7e629e1b72dd.png">

**Comment by jthegedus** [comment] 2020-05-13 22:32
Are you able to reproduce this with a different plugin, say nodejs? If you cannot reproduce, perhaps it is an erlang plugin issue?

**Comment by dkarter** [comment] 2020-05-19 17:41
I'm having the same issue here:
![2020-05-19 12 39 21](https://user-images.githubusercontent.com/551858/82359753-f2daea80-99cd-11ea-8112-f2fd081df212.gif)

**Comment by jthegedus** [comment] 2020-05-19 23:50
You may want to have a look here https://github.com/asdf-vm/asdf-erlang/issues/143

If this can be reproduced with another plugin, then it is an issue with the core, otherwise it should be discussed in the erlang plugin repo

**Comment by Stratus3D** [comment] 2020-05-20 14:02
This is a duplicate of https://github.com/asdf-vm/asdf-erlang/issues/143. This is not an issue with asdf core so let's continue the discussion on that ticket.

**Closed by Stratus3D** 2020-05-20 14:02 UTC
