### ISSUE TITLE
asdf.sh script bug with bash OSX sessions

### ISSUE THREAD

**Issue by gregors** [asdf-vm/asdf#92] opened 2016-09-08 13:51 UTC
on OSX El Capitan the asdf.sh logic to find the root directory doesn't work correctly since the terminal started outputting  "/Users/gregoryostermayr/.asdf Saving session... ...saving history...truncating history files... ...completed."

**Comment by Stratus3D** [comment] 2016-09-08 13:59
@gregors what version of asdf are you running? You can find out by either running `asdf --version` or by looking at the second line in ~/.asdf/lib/utils.sh

**Comment by gregors** [comment] 2016-09-09 14:22
"0.1" as per readme

**Comment by Stratus3D** [comment] 2016-09-12 13:52
I'm on Yosemite (10.10.5), and I am unable to replicate this issue. I know there is an bug in version 0.1 when it's used in a directory name that contains spaces, but it doesn't look like that is the same issue as yours. Are you using Zsh or Bash? Do you have your .bashrc/.zshrc posted somewhere so I could take a look at them?

**Comment by gregors** [comment] 2016-09-12 14:17
@Stratus3D you won't see this behavior on Yosemite only El Capitan - tries to be nice by adding a "global history"  aka Bash Sessions. see http://superuser.com/questions/975678/strange-output-from-terminal-exit-command-is-this-a-virus

**Comment by gregors** [comment] 2016-09-12 14:18
I'll take a stab at creating a fix and run it by you

**Comment by Stratus3D** [comment] 2016-09-13 19:03
Great! I don't have access to a machine running El Capitan right now so this is a huge help.

I'm hoping to tag the 0.2.0 release sometime in next couple of weeks, but I'll definitely want to get your fix merged before the release. If you have any questions about the codebase feel free to ask questions.

**Comment by philipgiuliani** [comment] 2016-09-23 07:06
I have the same problem on El Capitan :(

**Comment by HashNuke** [comment] 2016-09-25 15:46
@gregors did you find a fix? I'm not able to reproduce this on latest master with El Capitan.

**Comment by philipgiuliani** [comment] 2016-09-26 08:14
I fixed this bug by creating a file called `.bash_sessions_disable`. My sessions are still saved, so im not sure how this works.

@HashNuke could you check if you maybe have this file?

`touch ~/.bash_sessions_disable`

**Comment by HashNuke** [comment] 2016-10-02 21:32
@philipgiuliani I don't have the file. But I just came across the exact same issue on a colleague's computer last week and fixed it with some googling. I had to create that file.

I'm guessing the fix would have to be setting `SHELL_SESSION_HISTORY=0` whenever we run bash internally.

**Comment by gregors** [comment] 2017-04-07 19:13
@Stratus3D feedback appreciated

**Comment by gregors** [comment] 2017-04-11 22:39
@HashNuke @philipgiuliani I've got a fix without having to disable bash sessions

**Comment by gregors** [comment] 2017-05-01 14:55
ping

**Comment by jgonzalezd** [comment] 2017-06-10 03:16
I just had this problem. `touch ~/.bash_sessions_disable`solved the issue. (After one hour of googling and trying with my .bashrc and .bash_profile files)

**Comment by childnode** [comment] 2017-12-18 22:32
```
-bash:$ type cd
cd is a function
cd () 
{ 
    __zsh_like_cd cd "$@"
}
```

`unset cd` and you're gone ... without disabling the history ... which is not a "fix"

https://stackoverflow.com/questions/25381304/why-type-cd-on-mac-os-states-that-cd-is-a-function

**Comment by Stratus3D** [comment] 2018-03-13 13:07
@gregors can you check and see if you `cd` is actually a function?

**Comment by Stratus3D** [comment] 2018-07-15 02:39
Closing this issue since it's unclear if this is actually a bug in asdf. PR #334 may help us avoid this problem as we don't use `cd` when computing the `ASDF_DIR` path.

**Closed by Stratus3D** 2018-07-15 02:39 UTC
