### ISSUE TITLE
plugin-list --urls only works after plugin-list-all

### ISSUE THREAD

**Issue by matti** [asdf-vm/asdf#632] opened 2020-01-03 16:42 UTC
In fresh install

```
asdf plugin-list --urls
```
only outputs names and not urls.

**Comment by Stratus3D** [comment] 2020-07-20 15:57
Sorry for the late response. I can't reproduce this issue on my machine, and since others have not reported this same issue I'm assuming it was either fixed in a later release of asdf or was caused by something outside of asdf. Please let me know if this is still a problem.

**Closed by Stratus3D** 2020-07-20 15:57 UTC
