### ISSUE TITLE
Installing erlang 23.0.4 failed on macOS High Sierra

### ISSUE THREAD

**Issue by zhangzhen** [asdf-vm/asdf#824] opened 2020-11-08 00:12 UTC
**Describe the bug**

Installing erlang 23.0.4 failed on macOS High Sierra.

**To Reproduce**

Running `asdf install erlang 23.0.4` in the console.

**Expected behavior**

Installation succeeded.

**Actual behavior**
`LD     /Users/zhangzh/.asdf/plugins/erlang/kerl-home/builds/asdf_23.0.4/otp_src_23.0.4/lib/erl_interface/bin/x86_64-apple-darwin17.7.0/erl_call`
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1

### Environment

```shell
OS:
Darwin zhangzhendeMacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Mon Aug 31 22:11:23 PDT 2020; root:xnu-4570.71.82.6~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.3 (x86_64-apple-darwin17.0)

ASDF VERSION:
v0.8.0-c6145d0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/zhangzh/.asdf

ASDF INSTALLED PLUGINS:
elixir                       https://github.com/asdf-vm/asdf-elixir.git
erlang                       https://github.com/asdf-vm/asdf-erlang.git
```

**Screenshots**
![image](https://user-images.githubusercontent.com/782824/98453918-67326180-2199-11eb-83cc-97a37796d84a.png)

**Additional context**
```shell
~ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```shell
~ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-409.12
BUILD 17:47:51 Sep 25 2018
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 10.0.0, (clang-1000.10.44.4) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 10.0.0 (tapi-1000.10.8)
```

Here is my log file. 
[otp_build_23.0.4.log](https://github.com/asdf-vm/asdf/files/5505680/otp_build_23.0.4.log)

**Comment by Stratus3D** [comment] 2020-11-09 19:08
Closing as this is not an issue with asdf core, but rather an issue with asdf-erlang. This is also a duplicate of https://github.com/asdf-vm/asdf-erlang/issues/169

**Closed by Stratus3D** 2020-11-09 19:08 UTC
