### ISSUE TITLE
bug: npm -v takes 6 second to show version and `npm i` takes 1.5 hours.

### ISSUE THREAD

**Issue by xcfw** [asdf-vm/asdf#1284] opened 2022-06-30 11:17 UTC
### Describe the Bug

On system I have nix and asdf for development. And in home directory `npm -v` works fine, but in project dir it takes 6 seconds to load.

Tryed `rm -rf ~/.asdf/shims; asdf reshim` and updating asdf, it didn't help.

### Steps to Reproduce

1. asdf install nodejs 14.17.0
2. asdf local nodejs 14.17.0
3. npm -v
4. npm i

### Expected Behaviour

The same package.json on intel machine with linux install everything within 5 minutes. That is expected behaviour.

### Actual Behaviour

`npm install` in my project with only four git-repo dependencies and hundreds of npmjs deps (node 14, npm 6.14.4) taking about an hour and a half to perform on BigSur aarch64. Other asdf plugins work fine.
And it wasn't like that a week ago.

### Environment

```shell
OS:
Darwin Macas-MacBook-Air.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64 arm Darwin

SHELL:
zsh 5.8.1 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.10.2-7e7a1fa

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/macamarila/.asdf

ASDF INSTALLED PLUGINS:
awscli                       https://github.com/MetricMike/asdf-awscli.git main c645552
golang                       https://github.com/kennyp/asdf-golang.git master cc8bc47
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 05f99c3
python                       https://github.com/danhper/asdf-python.git master 57ef777
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 36117f5
```

### asdf plugins affected (if relevant)

nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 05f99c3

**Comment by xcfw** [comment] 2022-06-30 11:24
<details>
  <summary>home.nix</summary>
  Here's home-manager config
  
  ```nix
    { config, pkgs, lib, ... }:
  
  {
    home.stateVersion = "22.11";

    programs.direnv.enable = true;
    programs.direnv.nix-direnv.enable = true;
  
    programs.neovim = {
      enable = true;
 
       extraConfig = builtins.concatStringsSep "\n" [
        # this allows you to add lua config files
        ''
          lua << EOF
          let g:sqlite_clib_path = '${pkgs.sqlite.out}/lib/libsqlite3.dylib'
          EOF
        ''
      ];
  
      # install needed binaries here
      extraPackages = with pkgs; [
        # used to compile tree-sitter grammar
        tree-sitter
        gopls
        rust-analyzer
      ];
      plugins = with pkgs.vimPlugins; [
        sqlite-lua
        vim-which-key
        telescope-frecency-nvim
        vim-tmux-navigator
        vim-tmux-focus-events
        vim-tmux-clipboard
      ];
    };
  
    programs.tmux.enable = true;
    programs.alacritty.enable = true;
  
    # Htop
    programs.htop.enable = true;
    programs.htop.settings.show_program_path = true;
  
    home.packages = with pkgs; [
      # Some basics
      coreutils
      curl
      wget
      vifm
      fzf
      bat
      tree
      ripgrep-all
      ripgrep
      bpytop
      luajit
      luajitPackages.lua
      luajitPackages.luv
      luajitPackages.luarocks-nix
      luajitPackages.luasql-sqlite3
      luajitPackages.plenary-nvim
      cmake
      aspell
      sqlite
      stow
      tree-sitter
      redli
      mosh
      yarn
      fasd
      gawk
      python2
      python3
      mkcert
      nss
  
      #projects deps
      heroku
      fd
      jq
      purescript
      shared-mime-info
      postgresql.lib
      pgcli
      imagemagick6
  
      # Useful nix related tools
      cachix # adding/managing alternative binary caches hosted by Cachix
      # comma # run software from without installing it
      niv # easy dependency management for nix projects
      cargo
  
    ] ++ lib.optionals stdenv.isDarwin [
      cocoapods
      m-cli # useful macOS CLI commands
    ];
  
  }
  ```
  
</details>

**Comment by jthegedus** [comment] 2022-06-30 13:02
There are so many variables in this equation. I have a lot of questions.

>And it wasn't like that a week ago.

- Do you know what you have changed in the past week that may have caused this to break?
- Are the versions of asdf and nodejs plugin the same as a week ago?
- Are the versions of all plugins and asdf core the same on both Big Sur aarch64 & Intel Linux machine?
- If the plugin or core have changed in the last week, have you tried reverting to the versions you had previously working as expected? Do they still work?
- How is asdf integrated/used within your Nix setup? Your Nix Home doesn't list asdf, as someone who doesn't use Nix, how relevant is that information to use debugging this if asdf is not used within Nix? 

If you can provide answers to these questions you can help us narrow down whether this is an actual issue with asdf core, asdf nodejs plugin or not asdf.

The asdf version `v0.10.2-7e7a1fa` is the git tag for release `0.10.2` which was ~3 weeks ago.

The git commit shown for your `asdf-nodejs` plugin is from ~2 weeks ago.

So both the versions for the core and the nodejs plugin you list are from before you say anything was wrong. If you used the latest two weeks ago they would be the same as today.

I am inclined to think something else is the cause of your issue.

**Comment by jthegedus** [comment] 2022-07-17 07:56
Closing this issue for the reasons mentioned above, particularly

>So both the versions for the core and the nodejs plugin you list are from before you say anything was wrong. If you used the latest two weeks ago they would be the same as today.

**Closed by jthegedus** 2022-07-17 07:56 UTC
Labels: bug
