### ISSUE TITLE
"No preset version installed, Please install a version" when version is already installed [golang]

### ISSUE THREAD

**Issue by firelizzard18** [asdf-vm/asdf#914] opened 2021-04-03 23:05 UTC
**Describe the bug**

`asdf` tells me "no preset version installed, please install <version>" when that version is already installed.

**To Reproduce**

```shell
# asdf install
golang 1.16.2 is already installed
nodejs 14.13.0 is already installed
postgres 12.4 is already installed
protoc 3.15.6 is already installed
python 3.9.1 is already installed
ruby 2.6.6 is already installed
yarn 1.22.10 is already installed
# dlv version 
No preset version installed for command dlv
Please install a version by running one of the following:

asdf install golang 1.16.2

or add one of the following versions in your config file at HOME/.tool-versions
golang 1.15.1
# ls ~/.asdf/installs/golang/1.16.2/packages/bin/dlv 
HOME/.asdf/installs/golang/1.16.2/packages/bin/dlv*
# go install github.com/go-delve/delve/cmd/dlv@latest
# dlv version                                        
No preset version installed for command dlv
Please install a version by running one of the following:

asdf install golang 1.16.2

or add one of the following versions in your config file at HOME/.tool-versions
golang 1.15.1
```

**Expected behavior**

Delve should run

**Actual behavior**

I get a useless (and wrong) error message.

### Environment

```shell
OS:
Darwin Kalorme 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.0)

ASDF VERSION:
v0.8.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf

ASDF INSTALLED PLUGINS:
golang                       https://github.com/kennyp/asdf-golang.git
minio                        https://github.com/aeons/asdf-minio.git
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git
protoc                       https://github.com/paxosglobal/asdf-protoc.git
python                       https://github.com/danhper/asdf-python.git
redis                        https://github.com/smashedtoatoms/asdf-redis.git
ruby                         https://github.com/asdf-vm/asdf-ruby.git
yarn                         https://github.com/twuni/asdf-yarn.git
```

**Comment by jsmestad** [comment] 2021-04-16 18:00
I hit this as well with the Ruby plugin

**Comment by jthegedus** [comment] 2021-04-26 07:45
@jsmestad https://github.com/asdf-vm/asdf/issues/557 discusses this issue with regards to Ruby

**Comment by jthegedus** [comment] 2021-04-26 07:47
@firelizzard18 Can you try uninstalling the `golang` plugin, reinstalling it and reinstalling the particular version?

**Comment by firelizzard18** [comment] 2021-04-26 22:19
@jthegedus 

- I manually fixed my issue by adding `# asdf-plugin: golang 1.16.2` to the shim.
- A number of months ago I had a very similar issue with Ruby shims, but adding `# asdf-plugin: ruby x.y.z` to the shim did not work. I don't recall how I fixed it.
- It does happen with other golang binaries.
- `asdf reshim golang` fixed it (by adding `# asdf-plugin: golang 1.16.2`)

I understand why this might be difficult to fix directly, possibly infeasibly difficult. In that case, I think I would prefer a better error message. The current message is `No preset version installed for command dlv [...]]] running one of the following [...] asdf install golang 1.16.2`. I read this as "golang 1.16.2 is not installed", which is incorrect. At the least, this error message should be updated to something that is not correct. Ideally, I'd like to see the following:

```
The shim for command dlv is out of date
Please run `asdf reshim golang` to correct this
```

This would require detecting that `~/.asdf/installs/golang/1.16.2/packages/bin/dlv` exists. Second best would be:

```
Command dlv is not installed for golang 1.16.2
Please install dlv or add one of the following versions in your config file at HOME/.tool-versions
golang 1.15.1

If this is incorrect, please run `asdf reshim golang`
```

**Comment by jthegedus** [comment] 2021-04-27 07:14
@firelizzard18 Yes, we need to improve the error here. We need to identify between executing a shim that doesn't exist with an entire version of the root tool (golang) not existing.

I will close this issue since you resolved it with `asdf reshim golang` (which is expected behaviour and a userland requirement). I will create a new issue with your comments here about improving the error.

#557 outlines a similar issue (this error message is output) but with Ruby and a missing required shim which was caused by an upstream Ruby change.

**Closed by jthegedus** 2021-04-27 07:14 UTC

**Comment by pranavkedia** [comment] 2022-02-11 17:08
I faced the same problem. Here was my steps to fix the problem

- Ensured I have only one `asdf` by running `where asdf`
- Ensured I have the right version of golang tool chain.
- Ran `asdf reshim`
- In vscode using the command palette updated all the go tools, followed by vscode restart. Had to do this twice.

**Comment by kennyp** [comment] 2022-02-11 17:48
Yes, you're going to run into this issue when you do a `go install` under one version and then switch to a different directory with a different version of Go in your `.tool-versions`. We could play around with the shims, but mostly I avoid the issue by having the binaries that are used all over as a part of my [default packages](https://github.com/kennyp/asdf-golang#default-go-get-packages).

**Comment by eric-burel** [comment] 2022-09-06 15:28
For lost googlers: be careful not to have legacy settings such as a ".nvmrc", this message can mean that asdf is trying to use the version listed in your ".nvmrc" while it's not installed. Either remove the ".nvmrc" to replace by a ".tool-versions", install the required version of node, or update ".nvmrc" to a version that is installed on your machine.

**Comment by Claywd** [comment] 2023-06-27 21:33
for me the next time I run into this problem...

`vim ~/.asdf/shims/dlv`
`# asdf-plugin: golang 1.xx.xx`
`asdf reshim`

**Comment by cristianoliveira** [comment] 2023-09-12 09:55
> * asdf reshim

This actually was the only thing that worked for me, sadly, I tried all the builtin commands.

**Comment by piotrpalek** [comment] 2024-04-22 21:36
for anyone stopping by because they've got such an error with nodejs, check out: https://github.com/asdf-vm/asdf-nodejs/issues/295

**Comment by ardinusawan** [comment] 2024-07-10 03:57
https://github.com/asdf-vm/asdf/issues/914#issuecomment-1610249003

When execute `asdf reshim` the config ~/.asdf/shims/dlv is being resetted 🤔

**Comment by tim-field** [comment] 2024-09-16 07:18
I had this error after uninstalling versions outside of asdf ( i.e deleting manually from the file system )
Deleting each of these versions via asdf fixed the issue.
