### ISSUE TITLE
bug: asdf install gives error message about .tool-versions even when it exists

### ISSUE THREAD

**Issue by likwid** [asdf-vm/asdf#1312] opened 2022-07-27 18:09 UTC
### Describe the Bug

I am trying to use asdf install functionality to install plugins on the machine.

```
[buildkite-agent@ip-10-0-26-33 packer-rjg-buildkite-agent]$ ls -lah
... brevity ...
-rw-r--r-- 1 buildkite-agent buildkite-agent   13 Jul 27 17:59 .tool-versions
```
```
[buildkite-agent@ip-10-0-26-33 packer-rjg-buildkite-agent]$ asdf install
Either specify a tool & version in the command
OR add .tool-versions file in this directory
or in a parent directory
```

`.tool-versions` exists, and was created by asdf (using `asdf local packer 1.8.2`) on another machine, but when I commit it, the new machine doesn't seem to recognize that it exists.  If I manually type out `asdf install packer 1.8.2` it works fine.

### Steps to Reproduce

1. Add a .tool-versions to a repository
2. Go to another machine, and attempt to use `asdf-install` on the repository to install the dependencies found in .tool-versions.

### Expected Behaviour

I would expect that it would try to install whatever I have configured in .tool-versions

### Actual Behaviour

Either specify a tool & version in the command
OR add .tool-versions file in this directory
or in a parent directory

### Environment

```shell
[buildkite-agent@ip-10-0-26-33 packer-rjg-buildkite-agent]$ asdf info
OS:
Linux ip-10-0-26-33 5.10.130-118.517.amzn2.x86_64 #1 SMP Wed Jul 13 16:51:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.10.2-7e7a1fa

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/var/lib/buildkite-agent/.asdf
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=/var/lib/buildkite-agent/.tool-versions
ASDF_CONFIG_FILE=/var/lib/buildkite-agent/.asdfrc
ASDF_DATA_DIR=/var/lib/buildkite-agent/.asdf

ASDF INSTALLED PLUGINS:
packer                       https://github.com/asdf-community/asdf-hashicorp.git master bc4dec6
terraform                    https://github.com/asdf-community/asdf-hashicorp.git master bc4dec6
```
```


### asdf plugins affected (if relevant)

packer and terraform

**Comment by southwolf** [comment] 2022-07-29 09:58
I've got this too

**Comment by Stratus3D** [comment] 2024-12-17 20:22
@likwid sorry for the extremely late reply. I'm not sure what the issue is here. A couple things to try:

1. Update your plugins `asdf plugin update --all`
2. Upgrade to the latest version of asdf
3. Check your `.tool-versions` file and make sure the format is correct

If none of these solve your issue please let us know. Given the age of this issue I'm going to close it.

**Closed by Stratus3D** 2024-12-17 20:22 UTC
Labels: bug
