### ISSUE TITLE
plugin-test fails list-all but should not

### ISSUE THREAD

**Issue by tomdavidson** [asdf-vm/asdf#338] opened 2018-06-18 18:29 UTC
### Steps to reproduce

`asdf list-all [plugin-name] or invoking the script directly works as expected and on OSX.  Unfortunately, `asdf plugin-test` fails on list-all. This not reproducible on my Gnu/Linux machine but consistently happens in Travis CI OSX on all of my plugins:

- https://travis-ci.org/td7x
- https://github.com/asdf-vm/asdf-plugins/issues/31

### Expected behavior

if `asdf list-all [plugin-name]` works so should `asdf plugin-test`'s invocation of list-all

### Actual behavior

```shell
The command "asdf list-all terragrunt" exited with 0.
1.26s$ asdf plugin-test terragrunt ./ 'terragrunt --version'
Cloning into '/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/asdf.XXXX.MskuXBED'...
remote: Counting objects: 2994, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 2994 (delta 14), reused 29 (delta 13), pack-reused 2962
Receiving objects: 100% (2994/2994), 465.91 KiB | 5.48 MiB/s, done.
Resolving deltas: 100% (1580/1580), done.
Cloning into '/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/asdf.XXXX.MskuXBED/plugins/terragrunt'...
done.
FAILED: list-all did not return any version
The command "asdf plugin-test terragrunt ./ 'terragrunt --version'" exited with 1
```

### Environment

**OS**: OSX vs Travic CI

**asdf version**:  0.4.3 & 0.5.0

**Comment by vitalis** [comment] 2018-06-18 20:40
@tomdavidson I have the same issue, I noticed that `list-all` actually outputs nothing on travisci,
so `asdf list-all [plugin-name]` doesn't actually work on travisci
I'm investigating the reason

**Comment by vitalis** [comment] 2018-06-19 13:20
@tomdavidson 
The issue is github api rate limit
Solved by adding `GITHUB_API_TOKEN` env variable see:
https://travis-ci.org/vitalis/asdf-kubesec/jobs/394101176
https://github.com/vitalis/asdf-kubesec/blob/master/bin/list-all

**Comment by vic** [comment] 2018-08-30 06:30
@vitalis Thank you so much for tracing it down to that, we have so many plugins failing because of this rate limiting thing. I'll add a check on `plugin-test` and see if the plugin `list-all` command uses the GitHub API and then, just make sure it also sets an Authorization header. People should still add their token as a secret on their travis build, but having this test and documentation will certainly help reduce this kind of errors. Than you again!!

**Comment by vic** [comment] 2018-08-30 06:34
Checks added at a4fc43e682.

Closing this, please follow the instructions at https://github.com/asdf-vm/asdf/blob/master/docs/creating-plugins.md#github-api-rate-limiting and re-trigger your plugin's build.

Will close this, please re-open if needed.

**Closed by vic** 2018-08-30 06:34 UTC

**Comment by tomdavidson** [comment] 2018-09-03 19:29
@vic thank you for #a4fc43e  but I am not able to pass the check:

from travis, I now get:

```
Setting environment variables from repository settings
$ export GITHUB_API_TOKEN=[secure]
$ export CC=gcc
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
before_script.1
0.47s$ git clone https://github.com/asdf-vm/asdf.git
Cloning into 'asdf'...
before_script.2
0.00s$ . asdf/asdf.sh
0.69s$ asdf plugin-test terragrunt https://gitlab.com/td7x/asdf/terragrunt.git
Cloning into '/tmp/asdf.dhtu'...
done.
Cloning into '/tmp/asdf.dhtu/plugins/terragrunt'...
Looks like terragrunt/bin/list-all relies on GitHub releases
but it does not properly sets an Authorization header to prevent
GitHub API rate limiting.
See https://github.com/asdf-vm/asdf/blob/master/docs/creating-plugins.md#github-api-rate-limiting
FAILED: terragrunt/bin/list-all does not set GitHub Authorization token
The command "asdf plugin-test terragrunt https://gitlab.com/td7x/asdf/terragrunt.git" exited with 1.
```

and I have even used @vitalis list-all nearly verbatim (thank you @vitalis ):

``
`#!/usr/bin/env bash

set -e
set -o pipefail

releases_path=https://api.github.com/repos/gruntwork-io/terragrunt/releases
cmd="curl -s"
if [ -n "$GITHUB_API_TOKEN" ]; then
  cmd="$cmd -H 'Authorization: token $GITHUB_API_TOKEN'"
fi
cmd="$cmd $releases_path"

function sort_versions() {
  sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' | \
    LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | awk '{print $2}'
}

# Fetch all tag names, and get only second column. Then remove all unnecesary characters.
versions=$(eval $cmd | grep -oE "tag_name\": *\".{1,15}\"," | sed 's/tag_name\": *\"//;s/\",//' | sort_versions)
echo $versions
```

**Comment by vic** [comment] 2018-09-04 18:54
@tomdavidson you have to [create a token](https://github.com/asdf-vm/asdf/blob/master/docs/creating-plugins.md#github-api-rate-limiting) and make it available as `GITHUB_API_TOKEN` on your travis build settings.

**Comment by tomdavidson** [comment] 2018-09-04 23:36
Hi @vic I should have highlighted that I did, but you can see it from the travis log. I did a new commit to make sure the new env var was used in the job too.

```
Setting environment variables from repository settings
$ export GITHUB_API_TOKEN=[secure]
```

**Comment by vic** [comment] 2018-09-10 16:28
@tomdavidson looking at the travis log you pasted here, looks like you forgot to push your changes then, the test is failing because there is no Authorization header set on https://gitlab.com/td7x/asdf/terragrunt/blob/master/bin/list-all

**Comment by tomdavidson** [comment] 2018-09-10 22:45
https://gitlab.com/td7x/asdf/terragrunt/blob/travis-wip/bin/list-all

But you are still right - the test is cloning the master branch rather than the feature branch. Thank you!
