### ISSUE TITLE
Feature: Support asdf .plugin-versions

### ISSUE THREAD

**Issue by aabouzaid** [asdf-vm/asdf#1577] opened 2023-06-12 18:24 UTC
### Is your feature request related to a problem? Please describe

Currently, `asdf` doesn't provide a method to pin its plugin's URL and version. This creates 2 main issues:
1. Security-wise, the plugins are not secure unless manually added in 2 steps, first `asdf plugin add <name> [<git-url>]`, and second `asdf plugin update <name> [<git-ref>]`.
2. Operational-wise, unlike `.tool-versions`, it's not possible to set up asdf plugins declaratively, and it's hard to use it as part of Git/GitOps.

The `.plugin-versions` will be more or less the same format as `.tool-versions`, where the name, version/hash/tag, and URL will be set.

### Describe the proposed solution

There are many issues here in this repo as well as [asdf-plugins](https://github.com/asdf-vm/asdf-plugins) about the first point (security) (starting from #166 and ending with #1564, )

I believe introducing a new file called `.plugin-versions` should be the best solution for that without touching `.tool-versions`. That will reduce the complexity of the feature and avoid breaking changes in `.tool-versions`.

It can use what's in PR no. #1204 and build on top of it.

### Describe similar `asdf` features and why they are not sufficient

asdf doesn't support the suggested feature.

### Describe other workarounds you've considered

The current workaround is each user will create a make or bash script to manage asdf plugins in a secure way.

**Comment by hyperupcall** [comment] 2023-06-15 17:50
Looks related to #240 and #829

**Comment by aabouzaid** [comment] 2023-06-15 18:16
@hyperupcall Well, it looks like a popular request :grinning: 

Thanks for mentioning those issues :bow:
I will read those issues and probably will close this one since it looks duplicated.

**Comment by jthegedus** [comment] 2023-06-18 14:07
Closing as this is a duplicate of the aforementioned tickets.

**Closed by jthegedus** 2023-06-18 14:07 UTC
Labels: enhancement
