### ISSUE TITLE
Allow customizing the path of the global .tool-versions file

### ISSUE THREAD

**Issue by pgilad** [asdf-vm/asdf#1553] opened 2023-04-30 09:52 UTC
### Is your feature request related to a problem? Please describe

The current solution always clutters the user homedir with the `.tool-versions` (or name override) file

### Describe the proposed solution

I would like to have the ability to explicitly set the global `.tool-versions` alongside with it's path (would usually resort to `~/.config/asdf/.tool-versions` myself).
Alternatively - one can just state the base directory for the global `.tool-versions` file, and then it will allow the ability to use the base path alongside the `ASDF_DEFAULT_TOOL_VERSIONS_FILENAME` override variable.

### Describe similar `asdf` features and why they are not sufficient

None relevant

### Describe other workarounds you've considered

None relevant

**Comment by hyperupcall** [comment] 2023-04-30 12:00
If the problem is that `.tool-versions` automatically clutters the home directory, would you also consider #1351 a fix? Instead of having to set a variable, you can just put the file in `~/.config/asdf`.

**Comment by pgilad** [comment] 2023-04-30 13:43
#1351 doesn't handle the global `.tool-versions`. You need to modify https://github.com/asdf-vm/asdf/blob/master/lib/functions/versions.bash#LL23C18-L23C27 for that

**Comment by Stratus3D** [comment] 2024-12-17 20:02
I'm going to close this as I believe #1351 is what we intend to eventually support.

**Closed by Stratus3D** 2024-12-17 20:02 UTC
Labels: enhancement
