### ISSUE TITLE
Alphabetize tool-versions

### ISSUE THREAD

**Issue by aaronmallen** [asdf-vm/asdf#804] opened 2020-09-17 20:31 UTC
**Is your feature request related to a problem? Please describe.**
I am neurotic and would like plugins listed in `.tool-versions` to be alphabetized.

**Describe the solution you'd like**
When I have an existing `.tool-versions` file and do `asdf <global|shell|local> <plugin> <version>` I would like the added plugin to be alphabetized into the `.tool-versions` file instead of appended to the end of the file.

**Describe workarounds you've considered**
Currently I open the file after the fact and alphabetize it, or write the file manually and do `asdf install` or I ensure I install plugins in alphabetical order.

**Comment by jthegedus** [comment] 2020-09-18 00:21
I recall finding myself in the obscure position where the ordering in `.tool-versions` mattered, so whatever solution proposed for this should also allow users to toggle the alphabetization.

**Comment by aaronmallen** [comment] 2020-09-18 00:24
> I recall finding myself in the obscure position where the ordering in `.tool-versions` mattered, so whatever solution proposed for this should also allow users to toggle the alphabetization.

@jthegedus Mattered because of the code base it was in or mattered because it broke asdf?

**Comment by jthegedus** [comment] 2020-09-18 01:28
I think it was because one plugin relied on a shim provided by another plugin. I'll try and reproduce,

<details>
<summary>but as I recall:</summary>

`.tool-versions`:

```
pluignB 1
pluginA 1
```

B required a shim from A but tried to use the globally set version instead of the local. Doing:

```
pluginA 1
plguinB 1
```

resolved the issue.

I'm not familiar with every aspect of the asdf core codebase so could be mistaken, and this may have been an unrelated problem that I magically resolved.

**Comment by jthegedus** [comment] 2020-09-18 05:08
In the meantime `sort .tool-versions -o .tool-versions` will do the trick

**Comment by Stratus3D** [comment] 2020-09-18 21:01
I don't believe we should alphabetize tools in the `.tool-versions` file because of this outstanding issue (I think this may be the one you were thinking of @jthegedus ) https://github.com/asdf-vm/asdf/issues/196

**Comment by ghostsquad** [comment] 2020-12-24 00:00
please don't arbitrarily reorder this file. There are dependencies. An example of this is `golang` and any tool that installs using `go get`

**Comment by Stratus3D** [comment] 2021-01-13 15:13
Closing this issue as file order is the only way to handle dependencies. We can re-open in the future if we implement a better method of handling dependencies.

**Closed by Stratus3D** 2021-01-13 15:13 UTC
