### ISSUE TITLE
Version Installation Failed but Reinstallation Fails due to Existing Build

### ISSUE THREAD

**Issue by philippneugebauer** [asdf-vm/asdf#562] opened 2019-08-15 20:21 UTC
```
Erlang/OTP 20.3.8.22 (asdf_20.3.8.22) has been successfully built
Installing Erlang/OTP 20.3.8.22 (asdf_20.3.8.22) in /Users/user/.asdf/installs/erlang/20.3.8.22...
Couldn't install Erlang/OTP 20.3.8.22 (asdf_20.3.8.22) in /Users/user/.asdf/installs/erlang/20.3.8.22

$ asdf install erlang 20.3.8.22
There's already a build named asdf_20.3.8.22

$ asdf list erlang
22.0.7
```

I tried to find a build file named `asdf_20.3.8.22` but my Finder does not find anything with this name. What do I need to do to successfully (re)install this version?

### Environment

**OS**: macOS Mojave

**asdf version**: 0.7.4

**Comment by Stratus3D** [comment] 2019-10-25 21:10
Sorry for the late reply, I'm not able to reproduce this on my machine (MacOS Mojave 10.14.6) with the latest version of asdf and asdf-erlang. I believe a new version of kerl was released not too long ago. Output for me:

```
$ asdf install erlang 20.3.8.22
Downloading OTP-20.3.8.22.tar.gz to /Users/trevorbrown/.asdf/plugins/erlang/kerl-home/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    289      0 --:--:-- --:--:-- --:--:--   290
100 51.0M    0 51.0M    0     0  6133k      0 --:--:--  0:00:08 --:--:-- 6952k
Extracting source code
Building Erlang/OTP 20.3.8.22 (asdf_20.3.8.22), please wait...
DOCUMENTATION INFORMATION (See: /Users/trevorbrown/.asdf/plugins/erlang/kerl-home/builds/asdf_20.3.8.22/otp_build_20.3.8.22.log)
 * documentation  : 
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Erlang/OTP 20.3.8.22 (asdf_20.3.8.22) has been successfully built
Installing Erlang/OTP 20.3.8.22 (asdf_20.3.8.22) in /Users/trevorbrown/.asdf/installs/erlang/20.3.8.22...
You can activate this installation running the following command:
. /Users/trevorbrown/.asdf/installs/erlang/20.3.8.22/activate
Later on, you can leave the installation typing:
kerl_deactivate
Cleaning up compilation products for 
Cleaned up compilation products for  under /Users/trevorbrown/.asdf/plugins/erlang/kerl-home/builds

Erlang 20.3.8.22 has been installed. Activate globally with:

    asdf global erlang 20.3.8.22

Activate locally in the current folder with:

    asdf local erlang 20.3.8.22


$ asdf list erlang
  20.0
  20.2.3
  20.3.6
  20.3.8.22
  20.3
  21.3.2
  21.3.8.2
  21.3.8
```

**Comment by Stratus3D** [comment] 2019-10-25 21:12
Also maybe try running `asdf uninstall erlang 20.3.8.22` if your failed build got partially installed. The uninstall command should remove everything so you should be able to install the version a second time in the event of an error.

**Comment by baezanat** [comment] 2020-03-09 09:20
I am having the same problem. Where you able to solve it?

I installed asdf, then ran 
`asdf install erlang 22.0.7`

 but got a number of error messages and interrupted the build with `ctrl + c` (my bad). Then I installed some additional packages and tried to reinstalled, but when I run 

`asdf uninstall erlang 22.0.7`

 I get 'No such version`. 

Yet if I try to install it with 
`asdf install erlang 22.0.7`

 I get 

`There's already a build named asdf_22.0.7`.


If I run 

`asdf list erlang`

, only `22.2.8` is listed (not 22.0.7).

I thought of deleting the build file, but don't know how to do it. Following advice in a forum, I ran `kerl delete build 22.0.7` but I get `Command 'kerl' not found`.

**Comment by Stratus3D** [comment] 2020-03-27 13:05
@baezanat have you tried updating to the latest version of the Erlang plugin? `asdf plugin-update erlang`. I just tried to reproduce this I was unable to.

**Comment by merqlove** [comment] 2020-04-08 11:50
**Another way is to cleanup those OTP files:**

![Screenshot 2020-04-08 14 49 59](https://user-images.githubusercontent.com/18354/78781039-3cd0b980-79a8-11ea-9995-b3937df8f18c.png)

**Comment by Stratus3D** [comment] 2020-04-08 20:00
Closing because I do not believe there any existing issues with the asdf-erlang plugin. If anyone experiences this issue going forward please open an issue on defaults write com.apple.finder AppleShowAllFiles YES

**Closed by Stratus3D** 2020-04-08 20:00 UTC

**Comment by adamu** [comment] 2020-05-14 12:51
I managed to resolve this by removing the part-installed version from
* `.asdf/plugins/erlang/kerl-home/otp_builds`
* `.asdf/plugins/erlang/kerl-home/otp_installations`

then re-running `asdf install erlang $version`.

Possibly related to https://github.com/kerl/kerl/issues/236.
