### ISSUE TITLE
Unable to use asdf with electron-rebuild

### ISSUE THREAD

**Issue by ionull** [asdf-vm/asdf#442] opened 2019-01-26 06:32 UTC
### Steps to reproduce

Tell us what actions you performed before the issue occurred

Unable to use asdf with electron-rebuild: https://github.com/electron/electron-rebuild/issues/271

### Expected behavior

Tell us what should have happened

### Actual behavior

Tell us what happened instead

Error: No such plugin: nodejs

### Environment

**OS**: macOS 10.14.2

**asdf version**: v0.6.3

**Comment by Stratus3D** [comment] 2019-01-27 22:00
Can you please complete the issue template? It's not clear what the steps are to reproduce this issue.

If asdf printed `Error: No such plugin: nodejs` that means the Node.JS plugin has not been found. This could be due to it not having been installed, or due to some other issue preventing asdf from locating the plugin.

**Comment by ionull** [comment] 2019-01-28 08:06
https://github.com/electron/electron-rebuild/pull/273
Hi there, I am not sure it is that rebuild repo bug or not, can you check this pull request?

**Comment by Stratus3D** [comment] 2019-01-28 14:17
It's not our responsibly to investigate bugs or review PRs for other software. If there is a bug there it is the responsibility of those maintainers and not asdf maintainers. If you update this issue with all the steps necessary to reproduce it we will investigate. I'm closing this because it's not a valid issue. I'll reopen if you can provide more specifics on the issue.

**Closed by Stratus3D** 2019-01-28 14:17 UTC
Labels: invalid
