### ISSUE TITLE
asdf reshim create strange shim file and does not create shims directory

### ISSUE THREAD

**Issue by hurricup** [asdf-vm/asdf#791] opened 2020-08-31 14:23 UTC
**Describe the bug**

1. Cloned asdf according to the guide. (`git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0-rc1`
2. Installed ruby plugin
3. Installed ruby

For some reason `shims` directory was not created automatically.
After i've created it manually and ran `asdf reshim` i've got ruby shim:
```
#!/usr/bin/env bash
# asdf-plugin: ruby 2.7.1
exec ./.asdf/bin/asdf exec "ruby" "$@"
```
With relative path. Ofc, running it from inappropriate directory fails.

**Comment by jthegedus** [comment] 2020-09-03 07:34
I cannot recreate this Issue.

```shell
# clone
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0-rc1
# add to shell
# restart shell or source shell config
# add ruby plugin
asdf plugin add ruby
# install latest stable ruby version
asdf install ruby 2.7.1
# list shims dir
ls -la ~/.asdf/shims
# outputs
total 56
drwxr-xr-x  2 codespace codespace 4096 Sep  3 07:27 .
drwxr-xr-x 16 codespace codespace 4096 Sep  3 07:27 ..
-rwxr-xr-x  1 codespace codespace  101 Sep  3 07:27 bundle
-rwxr-xr-x  1 codespace codespace  102 Sep  3 07:27 bundler
-rwxr-xr-x  1 codespace codespace   98 Sep  3 07:27 erb
-rwxr-xr-x  1 codespace codespace   98 Sep  3 07:27 gem
-rwxr-xr-x  1 codespace codespace   98 Sep  3 07:27 irb
-rwxr-xr-x  1 codespace codespace   99 Sep  3 07:27 racc
-rwxr-xr-x  1 codespace codespace  101 Sep  3 07:27 racc2y
-rwxr-xr-x  1 codespace codespace   99 Sep  3 07:27 rake
-rwxr-xr-x  1 codespace codespace   99 Sep  3 07:27 rdoc
-rwxr-xr-x  1 codespace codespace   97 Sep  3 07:27 ri
-rwxr-xr-x  1 codespace codespace   99 Sep  3 07:27 ruby
-rwxr-xr-x  1 codespace codespace  101 Sep  3 07:27 y2racc 
```

Are you able to give us more information about your system setup? (`asdf update --head` will give get the latest version which includes the command `asdf info` which will print this useful information)

**Comment by hurricup** [comment] 2020-09-03 07:51
This is strange. This time shims dir created and ruby shim too, but it still uses relative path for some reason.
```
OS:
Linux HIVE 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.8.0-rc1-b178cb0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=./.asdf

ASDF INSTALLED PLUGINS:
ruby                         https://github.com/asdf-vm/asdf-ruby.git
```

**Comment by jthegedus** [comment] 2020-09-03 22:34
@hurricup That is strange. My system for instance prints:

```shell
ASDF VERSION:
v0.8.0-rc1-b178cb0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/jthegedus/.asdf
```

Perhaps `dirname` or `current_script_path` is not resolving on your system properly? Can you edit the file here https://github.com/asdf-vm/asdf/blob/master/asdf.sh#L15 to log `current_script_path` and also run `dirname ./asdf.sh` (from the `.asdf` dir)?

**Comment by jthegedus** [comment] 2021-04-27 07:29
Closing due to inactivity. Reopen if issue still persists and is reproducible.

**Closed by jthegedus** 2021-04-27 07:29 UTC
