### ISSUE TITLE
bug: lib/utils.bash: line 234: ASDF_.._VERSION: invalid variable name

### ISSUE THREAD

**Issue by jc00ke** [asdf-vm/asdf#1029] opened 2021-08-26 00:46 UTC
### Describe the Bug

When I run neovim latest `asdf` reports an invalid variable name.

### Steps to Reproduce

```
~
➜ nvim
/home/jesse/.asdf/lib/utils.bash: line 234: ASDF_.._VERSION: invalid variable name
```

### Expected Behaviour

Neovim would start with no error notice in the terminal.

### Actual Behaviour

I see this error message:

```
/home/jesse/.asdf/lib/utils.bash: line 234: ASDF_.._VERSION: invalid variable name
```

### Environment

```shell
OS:
Linux jimmie 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
fish, version 3.1.2

ASDF VERSION:
v0.8.1-a1ef92a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/jesse/.asdf

ASDF INSTALLED PLUGINS:
deno                         https://github.com/asdf-community/asdf-deno.git
dotnet-core                  https://github.com/emersonsoares/asdf-dotnet-core.git
elixir                       https://github.com/asdf-vm/asdf-elixir.git
elm                          https://github.com/asdf-community/asdf-elm.git
erlang                       https://github.com/asdf-vm/asdf-erlang.git
haskell                      https://github.com/vic/asdf-haskell.git
lua                          https://github.com/Stratus3D/asdf-lua.git
neovim                       https://github.com/richin13/asdf-neovim.git
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git
python                       https://github.com/danhper/asdf-python.git
redis                        https://github.com/smashedtoatoms/asdf-redis.git
ruby                         https://github.com/asdf-vm/asdf-ruby.git
rust                         https://github.com/code-lever/asdf-rust.git
shfmt                        https://github.com/luizm/asdf-shfmt.git
yq                           https://github.com/sudermanjr/asdf-yq.git
```
```


### asdf plugins affected (if relevant)

It might be one of the later plugins I have installed. Plugins that might be affecting it:

* dotnet-core
* haskell
* neovim (naturally)

**Comment by Kaylebor** [comment] 2021-11-24 20:56
I'm having the same issue, linked here asdf-vm/asdf-ruby#236

In my case it happens with Ruby instead, but other than that the symptoms are similar.

**Comment by augustobmoura** [comment] 2021-11-25 03:18
The problem (at least in my side) is that running reshim sometimes it (god knows why) adds a ghost plugin candidate `..` to the shim file and because the reshim script works it's never removed.

Print from my `npm` shim file for example:

![image](https://user-images.githubusercontent.com/5845160/143373245-294afa60-f3ba-4963-b6c5-b299050b09c2.png)

See those `asdf-plugin: ..`, those are the ones that are causing the issue.

The workaround for me is deleting the shim script and then reshimming:

```bash
rm "$ASDF_DIR/shims/npm" 
asdf reshim node
```

You might as well delete all others shims and reshim them all over again:

```bash
rm "$ASDF_DIR"/shims/*
asdf reshim
```

I don't know if this issue is because I keep messing with symlinks in the plugins dir, or because some bug in the past create them.

I think the solution should be cleaning these ghost plugins after reshims, or making a specific command for pruning/cleaning the shims directory

**Comment by augustobmoura** [comment] 2021-12-14 01:53
I tried to debug it, but the problem is that it is not consistent. I tried manually reshimming it sometimes but never got it to write `..` to any shim

**Comment by jc00ke** [comment] 2021-12-14 02:58
Does someone want to debug with me on my machine? It still does it.

**Comment by sheldonhull** [comment] 2022-01-25 20:51
This popped up for me and I have no idea what is causing it. 

```
⚙️ direnv global defaults: [bash]                                                                                                                                                      
direnv: ([/Users/USERNAME/.asdf/installs/direnv/2.30.3/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
/Users/USERNAME/.asdf/lib/utils.bash:234: ASDF_.DS_STORE_VERSION: invalid variable name
```

**Comment by bbenzikry** [comment] 2022-04-21 21:37
> This popped up for me and I have no idea what is causing it.
> 
> ```
> ⚙️ direnv global defaults: [bash]                                                                                                                                                      
> direnv: ([/Users/USERNAME/.asdf/installs/direnv/2.30.3/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
> /Users/USERNAME/.asdf/lib/utils.bash:234: ASDF_.DS_STORE_VERSION: invalid variable name
> ```

For me 
```bash
rm $ASDF_DATA_DIR/plugins/.DS_Store
``` 
seemed to do the trick

**Comment by lifeiscontent** [comment] 2022-05-02 21:10
@Stratus3D any ideas on why a .DS_Store file would interfer with something like this?

**Comment by Stratus3D** [comment] 2022-05-03 13:45
Thanks for the comments @sheldonhull and @bbenzikry ! I now understand what the problem is - in your case, somewhere in the code we are looping over all files in `$ASDF_DIR/plugins/` and assuming that each value is a plugin directory, but of course this is not necessarily true because a `.DS_Store` or any other type of file could end up in the `$ASDF_DIR/plugins/` directory. The proper fix is to only use the directories present in `$ASDF_DIR/plugins/`. I'm going to try and fix this this week.

**Comment by Kaylebor** [comment] 2022-05-03 13:55
@Stratus3D I had tried to fix that in December, but my approach was to clean up after :S

It worked for me, but I understand that didn't really fix the problem

Maybe [some parts of my approach](https://github.com/asdf-vm/asdf/pull/1099/files#diff-d9194658c29c645901d4be13b0b0ec41f0011024c396e3fcde815d5235d676c7R128) can be of use though, as I did use the plugins folder as reference of what would be valid metadata.

**Comment by xeger** [comment] 2022-05-09 17:51
**Update**: `asdf-vm` is not the root cause for my case; it's actually a [container virtualization bug](https://github.com/alpinelinux/docker-alpine/issues/156) in Alpine Linux 3.14 and has nothing to do with extra/missing files under `~/.asdf`. Upgrading to a newer Docker version, which contains a newer `runc`, fixed the issue in my case.

It does seem like ASDF has some circular error case, where a stub that is non executable causes bizarre error messages (because asdf is parsing its own error output to determine something about the shim). Not a big issue though, as long as one's shims are all proper.

**Comment by Stratus3D** [comment] 2022-05-11 12:15
@xeger thanks for the info.

@sheldonhull ping.

I've got a fix that I think will address the `.DS_Store` issue, unsure if it will address the root cause of this ticket - #1228. Can anyone on this issue check out that fix and see if it addresses the issue? It won't fix bad shims, but it should prevent bad shims from being generated.

**Comment by Stratus3D** [comment] 2022-05-12 11:51
I've merged a possible fix for this so if you want to test it run `asdf update --head`.

**Comment by Stratus3D** [comment] 2022-05-25 20:18
Closing as I've not gotten any responses on whether this issue still exists with the latest version. I will reopen if not resolved.

**Closed by Stratus3D** 2022-05-25 20:18 UTC
Labels: bug

**Comment by glasser** [comment] 2022-08-24 18:29
As a note, I'm getting this right now with `asdf` as installed from Homebrew at 0.10.2:

```
glasser@dsg-mbp 0 11:28:53 ~/Projects/Apollo/router bryn/ftv1 u= p= $ cat .envrc
use asdf
glasser@dsg-mbp 0 11:28:53 ~/Projects/Apollo/router bryn/ftv1 u= p= $ direnv reload
direnv: loading ~/Projects/Apollo/router/.envrc
direnv: using asdf
direnv: Creating env file /Users/glasser/.cache/asdf-direnv/env/45930459-3520607073-3344263149-1660765782
/usr/local/Cellar/asdf/0.10.2/libexec/lib/utils.bash:242: ASDF_.DS_STORE_VERSION: invalid variable name
direnv: loading ~/.cache/asdf-direnv/env/45930459-3520607073-3344263149-1660765782
direnv: using asdf nodejs 16.9.1
direnv: loading ~/.asdf/plugins/nodejs/bin/exec-env
direnv: using asdf rust 1.61.0
direnv: loading ~/.asdf/plugins/rust/bin/exec-env
direnv: export +CARGO_HOME +NPM_CONFIG_PREFIX +RUSTUP_HOME ~PATH```

**Comment by Stratus3D** [comment] 2022-08-24 18:59
@glasser please share the output of `asdf info`.

**Comment by glasser** [comment] 2022-08-24 22:00
```
 $ asdf info
OS:
Darwin dsg-mbp 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

SHELL:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.

ASDF VERSION:
v0.10.2

ASDF ENVIRONMENT VARIABLES:


ASDF INSTALLED PLUGINS:
direnv                       https://github.com/asdf-community/asdf-direnv.git master 5ad45d0
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
rust                         https://github.com/code-lever/asdf-rust.git master 0c88f99
```

Note that this is after I have deleted the DS_Store file and stopped the error.

**Comment by Stratus3D** [comment] 2022-08-25 17:45
@glasser what happens if you run `asdf reshim`? If that doesn't work could you share the contents of `~/.asdf/shims/direnv`?

**Comment by glasser** [comment] 2022-08-25 18:53
I'll let you know if it crops up again — I don't know how to induce OSX into creating a .DS_Store file.

**Comment by glasser** [comment] 2022-08-25 18:55
Ah actually, just opening `~/.adsf/plugins` in Finder seems to do it.

```
glasser@dsg-mbp 0 11:54:24 ~/Projects/Apollo/router main u-11 p-11 $ direnv reload
direnv: loading ~/Projects/Apollo/router/.envrc
direnv: using asdf
direnv: Creating env file /Users/glasser/.cache/asdf-direnv/env/45930459-3520607073-1811527558-1660765782
/usr/local/Cellar/asdf/0.10.2/libexec/lib/utils.bash:242: ASDF_.DS_STORE_VERSION: invalid variable name
direnv: loading ~/.cache/asdf-direnv/env/45930459-3520607073-1811527558-1660765782
direnv: using asdf nodejs 16.9.1
direnv: loading ~/.asdf/plugins/nodejs/bin/exec-env
direnv: using asdf rust 1.61.0
direnv: loading ~/.asdf/plugins/rust/bin/exec-env
direnv: export +CARGO_HOME +NPM_CONFIG_PREFIX +RUSTUP_HOME ~PATH
glasser@dsg-mbp 0 11:54:28 ~/Projects/Apollo/router main u-11 p-11 $ asdf info
OS:
Darwin dsg-mbp 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

SHELL:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.

ASDF VERSION:
v0.10.2

ASDF ENVIRONMENT VARIABLES:


ASDF INSTALLED PLUGINS:
direnv                       https://github.com/asdf-community/asdf-direnv.git master 5ad45d0
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master b2d06a7
rust                         https://github.com/code-lever/asdf-rust.git master 0c88f99

glasser@dsg-mbp 0 11:54:34 ~/Projects/Apollo/router main u-11 p-11 $ asdf reshim
glasser@dsg-mbp 0 11:54:40 ~/Projects/Apollo/router main u-11 p-11 $ direnv reload
direnv: loading ~/Projects/Apollo/router/.envrc
direnv: using asdf
direnv: Creating env file /Users/glasser/.cache/asdf-direnv/env/45930459-3520607073-3907766587-1660765782
/usr/local/Cellar/asdf/0.10.2/libexec/lib/utils.bash:242: ASDF_.DS_STORE_VERSION: invalid variable name
direnv: loading ~/.cache/asdf-direnv/env/45930459-3520607073-3907766587-1660765782
direnv: using asdf nodejs 16.9.1
direnv: loading ~/.asdf/plugins/nodejs/bin/exec-env
direnv: using asdf rust 1.61.0
direnv: loading ~/.asdf/plugins/rust/bin/exec-env
direnv: export +CARGO_HOME +NPM_CONFIG_PREFIX +RUSTUP_HOME ~PATH
glasser@dsg-mbp 0 11:54:47 ~/Projects/Apollo/router main u-11 p-11 $ cat ~/.asdf/shims/direnv 
#!/usr/bin/env bash
# asdf-plugin: direnv 2.31.0
exec /usr/local/opt/asdf/libexec/bin/asdf exec "direnv" "$@"
```
