### ISSUE TITLE
Weird "no preset version installed" message regarding powerline-config and python

### ISSUE THREAD

**Issue by HWiese1980** [asdf-vm/asdf#950] opened 2021-05-21 06:17 UTC
**Describe the bug**

In a particular folder I have a `.tool-versions` that contains a `python 3.9.2`. Furthermore I'm running Oh-My-Zsh with Powerlevel10K Theme and Powerline, that all works like a charm, so far, so good. Now, with this version pinned I'm getting the following weird message in a terminal opened in that particular folder with the pinned python version:

```bash
No preset version installed for command powerline-config
Please install a version by running one of the following:

asdf install python 3.9.2

or add one of the following versions in your config file at /Users/username/IdeaProjects/myideaproject/.tool-versions
python 3.8.7
``` 

I have python 3.8.7 and python 3.9.2 both installed in the local asdf library. Global python is set to 3.8.7. What I find weird about this is that according to the error message there's "no preset version installed for command **powerline-config**". That makes sense because as far as I know there is no asdf plugin for powerline (or at least I haven't found any yet). 

**To Reproduce**

I have no idea if this works. You could try the following... assuming that asdf has been properly set up already and does its job.

1. Set up a Oh-My-Zsh terminal (I'm on a MacBook with iTerm2)
2. Set up Powerlevel10k as style
3. Set up Powerline
4. Install Python 3.8.7 through asdf and set it as global python
5. Make a folder with a .tool-versions in it, pinning Python to 3.9.2
6. Switch to that folder
7. If the error is reproducible you should see it now

**Expected behavior**

Well, no error message in the first place. I've no idea what other consequences this might have. Python 3.9.2 is active in that folder, so no issue there.

**Actual behavior**

I'm seeing the mentioned error message. 

### Environment

```shell
OS:
Darwin MyMacBook.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,2 Darwin

SHELL:
zsh 5.8 (x86_64-apple-darwin20.0)

ASDF VERSION:
v0.8.0-c6145d0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/username/.asdf

ASDF INSTALLED PLUGINS:
awscli                       https://github.com/MetricMike/asdf-awscli.git
gomplate                     https://github.com/sneakybeaky/asdf-gomplate.git
gradle                       https://github.com/rfrancis/asdf-gradle.git
hadolint                     https://github.com/looztra/asdf-hadolint.git
java                         https://github.com/halcyon/asdf-java.git
jq                           https://github.com/AZMCode/asdf-jq.git
kotlin                       https://github.com/asdf-community/asdf-kotlin.git
maven                        https://github.com/halcyon/asdf-maven.git
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git
python                       https://github.com/danhper/asdf-python.git
sops                         https://github.com/feniix/asdf-sops.git
terraform                    https://github.com/Banno/asdf-hashicorp.git
terragrunt                   https://github.com/lotia/asdf-terragrunt.git
yq                           https://github.com/sudermanjr/asdf-yq.git
```

**asdf plugins affected (if relevant)**:

* python

**Screenshots**

**Additional context**

I have no idea how to figure out what versions of Powerlevel or Powerline10k I'm actually using.

**Comment by HWiese1980** [comment] 2021-05-21 06:24
### Additional information I've just figured out

```bash
$ which powerline-config
/Users/username/.asdf/shims/powerline-config
```

```bash
$ head $(which powerline-config)
#!/usr/bin/env bash
# asdf-plugin: python 3.8.7
exec /Users/username/.asdf/bin/asdf exec "powerline-config" "$@"
````

I'm not sure if that `asdf-plugin` line has any meaning other than just being a comment...

**Comment by NeoHsu** [comment] 2021-05-25 13:52
Hi @HWiese1980,
I think this problem is "Pip installed modules and binaries" issue,
I search installer [powerline tutorials](https://powerline.readthedocs.io/en/master/installation.html), it used pip to install,
maybe you can try this command `asdf reshim python` to changed module & package path

ref [asdf-python](https://github.com/danhper/asdf-python#pip-installed-modules-and-binaries)

**Comment by jthegedus** [comment] 2021-05-25 14:55
@HWiese1980 `asdf reshim python` is required after binaries are installed via `asdf-python` asdf @NeoHsu states.

Following your reproduction exactly would end in a bad state:

>1. Set up a Oh-My-Zsh terminal (I'm on a MacBook with iTerm2)
>2. Set up Powerlevel10k as style
>3. Set up Powerline
>4. Install Python 3.8.7 through asdf and set it as global python
>5. Make a folder with a .tool-versions in it, pinning Python to 3.9.2
>6. Switch to that folder
>7. If the error is reproducible you should see it now

Step 6 would put `asdf` in a state where it is trying to find `python 3.9.2` but you have not yet installed it. `3.8.7` is installed in step 4. Hence, the error message is correct.

You state earlier however that
>I have python 3.8.7 and python 3.9.2 both installed in the local asdf library.

Which is not the same as your reproduction steps.

>no preset version installed for command powerline-config

This shows as the error because your terminal is expecting to be able to execute the binary/library `powerline-config`. When you install an executable with `pip` or `npm` etc, the plugin which manages that installer, `asdf-python` or `asdf-nodejs`, creates a `shim` for that executable so it is available on your `$PATH`. Depending on the plugin you may have to run `asdf reshim <plugin_name>` as @NeoHsu suggested. The docs for each plugin will let you know.

The fact that there is a `powerline-config` entry in your `asdf` shims indicates that you have at some point installed `powerline-config` via `asdf`, probably via `pip`. It seems the `asdf` shim is trying to execute against a version of `python` not installed, so the command cannot be found.

**Comment by NeoHsu** [comment] 2021-06-03 17:27
This is no issue,

I think it has been answered.

Can we close it?

**Comment by HWiese1980** [comment] 2021-06-06 18:28
Sorry for getting back to you so lately. It's been a while since I stumbled across the problem. It is somehow caused by a `powerline-config` installation in my global (set via asdf) Python. That Python version is 3.8.7. The script gets called every time I open a shell, and it seems like it is trying to use the global Python environment, which is overridden by asdf evaluating a `.tool-versions` file in the current folder. The Python version in the `.tool-versions` is set to 3.9.2, which is installed too but does not have a `powerline-config`.

**Comment by HWiese1980** [comment] 2021-06-06 18:32
@jthegedus Thanks for summing it up. If I remember correctly, this is the way I installed my environment. I'll have to double check it. Do you maybe have a recommended way to fix it?

**Comment by jthegedus** [comment] 2021-06-06 22:32
I would suggest installing `powerline-config` is a way that doesn't rely on an `asdf` managed runtime/tool like Python.

**Comment by jthegedus** [comment] 2022-07-17 10:12
Closing this issue as it is a problem with using `asdf`-managed versions in Shell startup which requires consistent versions across directories which is antithetical with asdf.

**Closed by jthegedus** 2022-07-17 10:12 UTC
Labels: bug
