### ISSUE TITLE
asdf doesn't see openssl in MacOs

### ISSUE THREAD

**Issue by Peredery** [asdf-vm/asdf#934] opened 2021-05-08 21:30 UTC
**Describe the bug**

openssl@1.1 1.1.1k
```shell
% brew ls --versions openssl
openssl@1.1 1.1.1k
% which openssl
/usr/local/opt/openssl@1.1/bin/openssl
```
My .zshrc have this:
```bash
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
  export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
```

but asdf still install openssl every time :(
```shell
% asdf install ruby latest
Downloading openssl-1.1.1k.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/892a0875b9872acd04a9fde79b1f943075d5ea162415de3047c327df33fbaee5
```
And it's take too long

### Environment

!!!! **asdf install via git**
```shell
asdf info
OS:
Darwin Artyoms-Air 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.1.0)

ASDF VERSION:
v0.8.0-c6145d0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/peredery/.asdf

ASDF INSTALLED PLUGINS:
ruby                         https://github.com/asdf-vm/asdf-ruby.git
```

**asdf plugins affected (if relevant)**:
ruby, any where need to use openssl

**Comment by Stratus3D** [comment] 2021-05-20 19:22
@Peredery every plugin is different, and looks like this is specific to the Ruby plugin. The Ruby plugin uses ruby-build for installing rubies, so I suggest you take a look at the issue tracker for the ruby-build project if you think this is a bug - https://github.com/rbenv/ruby-build/issues?q=is%3Aissue+ssl+is%3Aopen.

If this is not a bug with ruby-build please open an issue in the https://github.com/asdf-vm/asdf-ruby repo. This is not a problem with asdf core, so I am closing this issue.

**Closed by Stratus3D** 2021-05-20 19:22 UTC
