### ISSUE TITLE
asdf plugin-test fails with "asdf: command not found"

### ISSUE THREAD

**Issue by virtualstaticvoid** [asdf-vm/asdf#346] opened 2018-08-08 16:10 UTC
### Steps to reproduce

Run tests on Travis CI with the following `.travis.yml` file for an asdf plugin such as [asdf-glooctl](https://github.com/virtualstaticvoid/asdf-glooctl).

E.g.

```yaml
language: c

script: asdf plugin-test glooctl https://github.com/virtualstaticvoid/asdf-glooctl.git

before_script:
  - git clone --branch v0.5.1 https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

os:
  - linux
```

### Expected behavior

`asdf plugin-test` should pass.

### Actual behavior

Fails with `asdf/lib/commands/plugin-test.sh: line 47: asdf: command not found`.

See build logs from some of my plugins. E.g.

* [asdf-glooctl](https://travis-ci.org/virtualstaticvoid/asdf-glooctl/builds/413642318) 
* [asdf-helm](https://travis-ci.org/virtualstaticvoid/asdf-helm/builds/413642557)
* [asdf-istioctl](https://travis-ci.org/virtualstaticvoid/asdf-istioctl/builds/413643059)

### Environment

**OS**: linux - Ubuntu Trusty (Travis CI)

**asdf version**: v0.5.1

### Possible Fix

I experimented by removing the line `cd "$ASDF_DIR" || fail_test "could not cd $ASDF_DIR"
` from [lib/commands/plugin-test.sh#L45](https://github.com/asdf-vm/asdf/blob/master/lib/commands/plugin-test.sh#L45) and it behaves as expected.

**Comment by Stratus3D** [comment] 2018-08-10 21:47
Test pass on my OSX machine without error. I ran that same command (`asdf plugin-test glooctl https://github.com/virtualstaticvoid/asdf-glooctl.git`) and it worked without any errors. The error you got makes it seem like `asdf` wasn't setup properly. I don't think this is due to a bug in `plugin-test.sh`.

**Comment by virtualstaticvoid** [comment] 2018-08-11 07:12
Yes, I found that it works locally for me too. I'll spend some more time trying to figure out why it fails when executing on Travis CI.

**Comment by cgrs** [comment] 2018-08-23 10:55
It's also happening to me, only on Linux environment: https://travis-ci.org/cgrs/asdf-haxe/jobs/419589566#L440

**Comment by vassilevsky** [comment] 2018-08-28 12:50
I thought that this might be caused by Travis running every command in isolation.
I tried putting all commands together to make Travis run them all in one shell:
```yaml
script: git clone https://github.com/asdf-vm/asdf.git &&
        . asdf/asdf.sh &&
        asdf plugin-test maven https://github.com/skotchpine/asdf-maven.git
```
This does NOT help. The error stays the same.

**Comment by vic** [comment] 2018-08-30 06:37
Fixed this at commit 950853.

Turns out the `asdf` command was not available on PATH, haha, so I just made sure the test is run an new subshell and we `source asdf.sh` within it.

I'm closing this, please re-trigger your plugin build and see if this has been fixed, if not, please re-open.

**Closed by vic** 2018-08-30 06:37 UTC

**Comment by virtualstaticvoid** [comment] 2018-08-30 14:05
I can confirm that [it works](https://travis-ci.org/virtualstaticvoid/asdf-glooctl/jobs/422572405) now.

Thanks @vic!

**Comment by vassilevsky** [comment] 2018-08-31 08:00
Yes, there is no problems in the builds now 👌💯
