### ISSUE TITLE
bug: asdf local python version is overridden by global python system

### ISSUE THREAD

**Issue by g-kartik** [asdf-vm/asdf#1156] opened 2022-01-13 03:47 UTC
### Describe the Bug

I have python 3.10.1 installed in my system. I ran ```asdf global python system``` to set that as global. However after setting my local python version using ``asdf local python 3.9.7```, my local python version still refers to the system python. 

### Steps to Reproduce

1. ```asdf global python system```
2. ```asdf local python 3.9.7```
3. Check python version in same local directory
4. Local system is not 3.9.7, instead it is the system version 3.10.1

### Expected Behaviour

The local version should not be overriden by the global system version for python

### Actual Behaviour

The local version should be what is defined by ```asdf local python``` irrespective of global system version

### Environment

```shell
OS:
Linux man 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux

SHELL:
fish, version 3.3.1

ASDF VERSION:
v0.9.0-9ee24a3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/gkrj/.asdf

ASDF INSTALLED PLUGINS:
python                       https://github.com/danhper/asdf-python.git master 57a4d72
```

**Comment by jthegedus** [comment] 2022-07-17 15:52
Closing this issue as:
- no participation from other users to the OP, comments or reactions
- core member could not reproduce issue on a later version of asdf
- no follow up from OP in 6 months

If you find yourself here, after reproducing on the latest version of asdf, please open an new Issue following all Issue creation instructions.

**Closed by jthegedus** 2022-07-17 15:52 UTC
Labels: bug
