### ISSUE TITLE
There is no way to silence spurious "No version set for command" warnings.

### ISSUE THREAD

**Issue by lexicalunit** [asdf-vm/asdf#838] opened 2020-12-17 22:41 UTC
**Describe the bug**

I do not want `asdf` to spam my shell with warnings about no version being set for a particular command. For example, I have `ruby 2.7.2` installed. When I switch into a directory with that plugin and version set, `asdf` correctly switches to use the correct version. Nice.

However when I'm outside of a directory without that plugin version set, for example my `~` home directory, I get this junk:

```shell
No version set for command ruby
Consider adding one of the following versions in your config file at
ruby 2.7.2
$ 
```

Yes. I know I don't have a version set. That's intended. I want to fallback to using the system installed `ruby`. I don't want to put a `.ruby-version` file in my home directory, thank you very much.

**To Reproduce**

1. Install `asdf` and the `ruby` plugin.

    ```shell
    brew install asdf
    asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
    asdf install ruby 2.7.2
    echo "legacy_version_file = yes" > ~/.asdfrc
    ```

1. Add the following to your `~/.profile` file in the correct place:

    ```shell
    ASDF_PREFIX="$(brew --prefix asdf 2>/dev/null || true)"
    if [[ -d "$ASDF_PREFIX" ]]; then
        # shellcheck disable=SC1090
        source "$ASDF_PREFIX/asdf.sh"
    fi
    ```

1. Open a new shell. Before the first prompt you will see the spurious junk.
1. Hit <kbd>enter</kbd> a few times. You'll get this junk before **every single prompt**. 😨

**Expected behavior**

There should be a way to disable this. I tried:

```shell
source "$ASDF_PREFIX/asdf.sh" &> /dev/null
```

But to no avail.

**Actual behavior**

I get a spurious warning before my shell terminal prompt. For every single prompt. Watch what happens if I just hit <kbd>enter</kbd> a few times:

```
No version set for command ruby
Consider adding one of the following versions in your config file at
ruby 2.7.2
$
No version set for command ruby
Consider adding one of the following versions in your config file at
ruby 2.7.2
$
No version set for command ruby
Consider adding one of the following versions in your config file at
ruby 2.7.2
$
No version set for command ruby
Consider adding one of the following versions in your config file at
ruby 2.7.2
$
```

What the heck?

### Environment

```shell
OS:
Darwin work 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin

SHELL:
zsh 5.8 (x86_64-apple-darwin19.6.0)

ASDF VERSION:
v0.8.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf

ASDF INSTALLED PLUGINS:
ruby                         https://github.com/asdf-vm/asdf-ruby.git
```

**asdf plugins affected (if relevant)**:

- `ruby`

At least that's the only plugin I've checked. But I think this is generic behavior for all plugins? Maybe?

**Comment by lexicalunit** [comment] 2020-12-17 22:50
It looks like these lines are the culprit: https://github.com/asdf-vm/asdf/blob/ac1a35b85bde049b9e2d531032eb55534e38ffe7/lib/utils.bash#L782

I need to disable those `printf` calls. I honestly don't see why they exist in the first place.

**Comment by lexicalunit** [comment] 2020-12-17 22:54
Wait. What the heck. I commented out those `printf` calls but it seems that this line https://github.com/asdf-vm/asdf/blob/ac1a35b85bde049b9e2d531032eb55534e38ffe7/lib/utils.bash#L785 also prints out some junk. For me it's printing out `ruby 2.7.2`. And when I comment it out `asdf` seems to break. Now when I start a new shell:

```shell
$ ruby
# exit code 126, command not found

$ command -v ruby
/Users/me/.asdf/shims/ruby
```

😬

**Comment by lexicalunit** [comment] 2020-12-17 23:01
I finally worked around this by adding 

```
ruby system
```

to the file `~/.tool-versions`. It's most disconcerting that I have to create a file in my home directory to resolve this issue.

**Comment by jthegedus** [comment] 2020-12-18 07:42
Thanks for reporting @lexicalunit , I am able to reproduce (with `nodejs` plugin) this behaviour as well (excpet for "spurious warning on before my shell terminal prompt. For every single prompt", for me it is only on shell login which may be because I am using `.zshrc` and not `.profile`, I am not too sure of this part)

As for the issue happening at all, it arises from no default version being found and is resolved by creating the `$HOME/.tool-versions` which is where asdf looks for global default values (this file can be configured which you will see https://asdf-vm.com/#/core-configuration)

>It's most disconcerting that I have to create a file in my home directory to resolve this issue.

This requirement should be _no more_ disconcerting than our requirement of the `$HOME/.asdfrc`. It is confusing however for users who have set `legacy_version_file`, I suspect this is either poor communication about a requirement OR an edge case.

This is an unhelpful error message because it usually lists the last config file it looked for a version in, but because no file is found it just says:

>Consider adding one of the following versions in your config file at

instead of

>Consider adding one of the following versions in your config file at /home/jthegedus/.tool-versions

---

These are the changes we will need to resolve this issue:

1. clarify if `legacy_version_file = yes` should remove the need of a `$HOME/.tool-versions` 
2. clarify if `$HOME/.tool-versions` is a required part of the setup (I have always thought that it was but may be mistaken)
3. when no config file exists up the entire filesystem tree, report a different error than if a config file is found but with no entry for the particular plugin

**Comment by jthegedus** [comment] 2020-12-18 21:59
`asdf` is only aware of commands and tries to control their versioning if there is a shim for that command. So if you have installed a plugin that creates a shim for `yarn`, then this is expected behaviour. If you have not installed a plugin that manages `yarn` then this is an issue with your setup as `asdf` should not be doing this without your specifically allowing it so. We have gone to great lengths to not automate setup of the tool to allow different users with different needs to manage their own configuration, this comes with more steps during setup.

Being the first user to experience this particular issue, it leads me to think there is an issue with your configuration.

From what I gather from the initial information you shared, the only difference I can see is your use of `~/.profile` instead of `~/.zshrc`. I would suggest moving

```
ASDF_PREFIX="$(brew --prefix asdf 2>/dev/null || true)"
if [[ -d "$ASDF_PREFIX" ]]; then
    # shellcheck disable=SC1090
    source "$ASDF_PREFIX/asdf.sh"
fi
```

from `~/.profile` to your `~/.zshrc`, closing all shells, logging out of your user on your machine and then trying again.

I am unfamiliar with edge cases of using `~/.profile` as we have built and tested `asdf` with the specific setups as noted in the documentation - https://asdf-vm.com/#/core-manage-asdf - of which using `~/.profile` is not one.

We have very clear documentation for specific machine configurations on our documentation site, so I would recommend following those closely as the order of steps matters (setting up asdf in your shell config before using it to add plugins). We also advise against using Homebrew as it can cause issues (again noted in the documentation).

**Comment by lexicalunit** [comment] 2020-12-20 17:58
Sorry, you're right. Somehow I have a bunch of plugins installed now:

```shell
$asdf plugin list
golang
minio
nodejs
postgres
redis
ruby
yarn
```

I honestly don't know how those got installed. I think maybe some bootstrap process in a work script might have done it? I only ever personally installed the `ruby` plugin myself.

**Comment by jthegedus** [comment] 2020-12-20 21:54
>maybe some bootstrap process in a work script might have done it

Perhaps advise the script author to log what it is configuring on your system.

**Comment by whurd-redcanary** [comment] 2021-02-08 15:22
Also, this output is confusing - https://github.com/asdf-vm/asdf/blob/bd21c99a0a04018b51e528acff8d237bff8780c4/lib/utils.bash#L786 

It doesn't print the path to the config file 

The test seems to be correct https://github.com/asdf-vm/asdf/blob/bd21c99a0a04018b51e528acff8d237bff8780c4/test/shim_exec.bats#L93

**Comment by jthegedus** [comment] 2021-05-04 01:16
Closing as this issue seemed to be a side-effect of some automated setup script shared in a workplace.

If other users start seeing these specific circumstances crop up, then feel free to reopen.

@whurd-redcanary If you're still experiencing an issue, please open a new issue.

**Closed by jthegedus** 2021-05-04 01:16 UTC
Labels: bug

**Comment by starrybleu** [comment] 2021-06-30 09:19
> Also, this output is confusing -
> 
> https://github.com/asdf-vm/asdf/blob/bd21c99a0a04018b51e528acff8d237bff8780c4/lib/utils.bash#L786
> 
> It doesn't print the path to the config file
> 
> The test seems to be correct
> 
> https://github.com/asdf-vm/asdf/blob/bd21c99a0a04018b51e528acff8d237bff8780c4/test/shim_exec.bats#L93

For future readers,

I also got "No version set for ruby", when I tried to start codedeploy-agent which is run with ruby.
I have installed asdf into /opt/asdf in order that every user can use it.

After reading and applying whurd-redcanary's hint, I figured out that codedeploy-agent's $PROJECT_DIR is just `/`.
So I added a file `/.tool-verions` with content `ruby 2.3.3` (yes, it's too old. it's not important here), then worked like charm!

**Comment by reverseCodeMosis** [comment] 2021-08-12 06:24
https://gifer.com/3qPG
