### ISSUE TITLE
Prevent from uninstalling a runtime if it is being used in a project.

### ISSUE THREAD

**Issue by stormwatch** [asdf-vm/asdf#1160] opened 2022-01-13 22:23 UTC
### Is your feature request related to a problem? Please describe

Hi. Thank you all for making and maintaining asdf.

This is just a personal itch. After a while, I would end up with different versions of various runtimes; and then I would have a hard time trying to remember which ones I still need to keep and which ones I can safely uninstall.

### Describe the proposed solution

I am thinking of a command that provides a list of directories where a particular runtime is used, instead of chasing ` .tool-versions` all around my projects. Maybe it can be an `asdf list` option, something like `asdf list --projects`, 

But maybe it could be even a little better. Maybe there is a way to mark a runtime as protected whenever an `asdf local <runtime> <version>` is run; and prevent me from uninstalling it (unless I pass an option like `--force`)

### Describe similar `asdf` features and why they are not sufficient

`asdf list` seems like a good candidate for including a `--projects` option

`asdf uninstall <plugin> <version>` should fail if I have a project in which `asdf local <plugin> <version>` was run.

### Describe other workarounds you've considered

I cannot think of anything right now; but I am hoping you will.

**Comment by Stratus3D** [comment] 2022-01-21 14:52
This is a duplicate of https://github.com/asdf-vm/asdf/issues/819

There are too many edges cases for it to be worth implementing this in asdf itself (think symlinks, directory permissions, mounted disks, etc...) and it can easily be done outside of asdf. See this comment here for the solution - https://github.com/asdf-vm/asdf/issues/819#issuecomment-852449294

**Closed by Stratus3D** 2022-01-21 14:52 UTC
Labels: enhancement
