### ISSUE TITLE
bug: cmds that result in no change should return exit status 0

### ISSUE THREAD

**Issue by Ecco** [asdf-vm/asdf#1163] opened 2022-01-18 22:30 UTC
### Describe the Bug

`asdf install` will exit with a zero return code if all tools are already installed. That's great.
But then `asdf add plugin nodejs` will return with an exit code of -2 if the nodejs plugin is already installed. That's inconsistent.

I don't mind if either of those return `-2` or `0`, but I think they should be consistent and return the same value.

### Steps to Reproduce

1. `asdf install`
2. Type again `asdf install`
3. See how the return code is `0`
4. `asdf plugin add nodejs`
5. Type again the same command
6. See how it returns `-2`

### Expected Behaviour

Both commands should return the same code.

### Actual Behaviour

They don't.

### Environment

```shell
OS:
Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.9.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/homebrew/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master ed34355
ruby                         https://github.com/asdf-vm/asdf-ruby.git master d0e5a20
```

**Comment by jthegedus** [comment] 2022-07-17 15:33
Closing as duplicate of #841

**Closed by jthegedus** 2022-07-17 15:33 UTC
Labels: proposal
