### ISSUE TITLE
asdf install does not recursively use .tool-versions

### ISSUE THREAD

**Issue by olafrauch** [asdf-vm/asdf#535] opened 2019-06-05 12:11 UTC
### Steps to reproduce

~/tmp # asdf -v
version: v0.7.2
...

~/tmp # asdf plugin-add consul
Cloning into '/usr/share/asdf/data/plugins/consul'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 57 (delta 0), reused 0 (delta 0), pack-reused 56
Unpacking objects: 100% (57/57), done.

~/tmp # asdf plugin-add vault
Plugin named vault already added

~/tmp # echo consul 1.5.1 > .tool-versions
~/tmp # cd subproject/
~/tmp/subproject # echo vault 1.1.0 > .tool-versions

~/tmp/subproject # asdf install
Downloading vault version 1.1.0 from https://releases.hashicorp.com/vault/1.1.0/vault_1.1.0_linux_amd64.zip
Cleaning vault previous binaries
Creating vault bin directory
Extracting vault archive

~/tmp/subproject # cd ..
~/tmp # asdf install
Downloading consul version 1.5.1 from https://releases.hashicorp.com/consul/1.5.1/consul_1.5.1_linux_amd64.zip
Cleaning consul previous binaries
Creating consul bin directory
Extracting consul archive
~/tmp #

### Expected behavior

Both tools (consul & vault) should be installed when calling asdf install in the subproject.
Means: Both .tool-versions should be read (parent and sub directory)

### Actual behavior

Only the tool referenced in the .tool-versions in the sub directory is installed

### Environment

**OS**: RHEL 7

**asdf version**: 0.7.2

**Comment by Stratus3D** [comment] 2019-06-21 14:15
I'm not able to reproduce this issue. It's possible that the `vault` installation is exiting with a non-zero exit code and halting the installation. This is by design, since the user may not want to continue if a plugin fails to install. I do not use either of those plugins so I'm not sure how they behave.

**Comment by olafrauch** [comment] 2019-06-21 18:44
I used `vault` and `consul`as a sample. 
The same behaviour happens with other tools too.
Just retested it with `terraform` in the sub project.

The sympom is, that only the `.tool-versions` file in the subproject is evaluated and the file in the parent directory is ignored when executing `asdf install`

**Comment by Stratus3D** [comment] 2019-06-21 19:26
I think we have tests for this. I need to investigate why they are not catching this.

**Comment by HashNuke** [comment] 2020-10-07 03:45
Summarizing the issue:
* Current directory has `.tool-versions` file with `package1`
* Parent directory has `.tool-versions` file with `package2`

The reported issue seems to be about not installing `package2` when running `asdf install` in the current directory. This is expected behaviour that only the current directory's `.tool-versions` file is respected during install.

If we go with the expected behaviour from the issue reported, asdf will have to parse through the directory hierarchy to identify all the `.tool-versions` files and merge it. I would say that such an implementation/use-case is not necessary for asdf to handle.

Closing the issue. Please feel free to continue discussion and reopen if appropriate.

**Closed by HashNuke** 2020-10-07 03:45 UTC
Labels: help wanted

**Comment by jthegedus** [comment] 2020-10-09 07:55
Test cases covering this scenario and doc improvements would indicate expected behaviour to users.

**Comment by eric-burel** [comment] 2022-09-06 08:28
Hey folks sorry to dig this old issue, but I've noticed that if a subdirectory doesn't have a ".tool-versions", asdf doesn't seem to enable "node" in this subdirectory, while it works fine in the parent directory that has a ".tools-version".

Do we have to run some command so that "node" is available in any subdirectory of a directory that has a ".tools-version"? Maybe I need to run "asdf global"?
