### ISSUE TITLE
Consider moving home config files to standardized XDG_CONFIG location

### ISSUE THREAD

**Issue by brennanfee** [asdf-vm/asdf#844] opened 2020-12-31 04:55 UTC
Currently, the dotfiles (.tool-versions file as well as any plugin specific default files - such as .default-gems or .default-npm-packages) all live in the $HOME folder.

Consider moving those to the approved and standardized config location (XDG_CONFIG).  Perhaps "$XDG_CONFIG/asdf/" would be an appropriate location with a hard-coded "~/.config/asdf/" as a fallback when XDG_CONFIG is not set.  For backward compatibility the tool could futher fall back to the current locations for some time to allow people time to transition.

**Comment by Stratus3D** [comment] 2021-01-05 15:45
Related: 

* https://github.com/asdf-vm/asdf/issues/201
* https://github.com/asdf-vm/asdf/issues/687

This ticket actually seems like a duplicate of https://github.com/asdf-vm/asdf/issues/687, with a more specialized use case (XDG_CONFIG instead of any location). Can I close this ticket @brennanfee and continue discussion on #687 ?

**Comment by brennanfee** [comment] 2021-01-27 14:00
@Stratus3D Yes, feel free to close this ticket.  I would STRONGLY encourage that #687 be updated to refer to and use XDG_CONFIG as its implementation.  Given that it has become a standard on nearly all Linux distributions and if implemented with a default when NOT set can work equally well on Mac and Windows.

For reference here is the "official" documentation:  https://www.freedesktop.org/wiki/Software/xdg-user-dirs/

**Closed** 2021-01-28 17:06 UTC
