### ISSUE TITLE
"asdf list" sorting incorrectly, broken by version prefix "v"?

### ISSUE THREAD

**Issue by larham** [asdf-vm/asdf#923] opened 2021-04-16 17:39 UTC
Although the [`yq` plugin](https://github.com/larham/asdf-yq) sorts versions correctly, `asdf list yq` erroneously lists an old version. The underlying issues seems to be that the `yq` developer added a prefix "v" to latest releases (v4.0+).  Note: the command `sort -V` has correct behavior in this case.

**To Reproduce**

```
$ asdf plugin add yq

# this shows that the yq plugin lists versions in correct order, despite the "v" prefix on some releases
$ asdf list all yq
3.1.2
... # snip
4.0.0
v4.1.0
v4.2.0
... # snip
v4.7.0

# this is the problem: 
$ asdf list yq
  4.0.0
```

**Expected behavior**

`asdf` should list the latest version when given a list of correctly sorted releases by the plugin:

```
$ asdf list yq
  v4.7.0
```

**Actual behavior**

It lists an old version.

```
# this is the problem: 
$ asdf list yq
  4.0.0
```

Note that the "sort" command has a -V option which will sort these correctly.

`curl -fsS --url https://api.github.com/repos/mikefarah/yq/releases | jq -r '.[].tag_name' |sort -rV |head -1`

**Comment by cho-m** [comment] 2021-04-23 03:21
`asdf list` will list all versions you installed. Based on some quick tests, there are no issues here.
```console
❯ asdf list yq
  4.0.0
  v4.7.0

❯ asdf list python
  3.9.2
  3.9.4
```
---

`asdf latest` will try to list the latest version available.

This is known to have limitations and there is already an open feature request by ASDF members to defer the logic to the plugins. See: https://github.com/asdf-vm/asdf/issues/763

There is also an older issue related to `v` versions for `latest` command: https://github.com/asdf-vm/asdf/issues/849

**Comment by jthegedus** [comment] 2021-04-27 07:52
Closing as it's a duplicate of #849 with more discussion. #763 is the tracking for the original bug report which #849 is essentially a duplicate of.

**Closed by jthegedus** 2021-04-27 07:52 UTC

**Comment by larham** [comment] 2021-04-29 16:05
@cho-m Thanks very much for explaining the root issue and pointing me to the source.
