### ISSUE TITLE
Not all tools gets installed on `asdf install`

### ISSUE THREAD

**Issue by nicktime** [asdf-vm/asdf#410] opened 2018-11-29 08:11 UTC
### Steps to reproduce
```
$ cat .tool-versions 
erlang 19.3.6.4
ruby 2.2.9
$ asdf plugin-list
erlang
ruby
$ asdf install
Extracting source code
Building Erlang/OTP 19.3.6.4 (asdf_19.3.6.4), please wait...
APPLICATIONS DISABLED (See: /home/nick/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3.6.4/otp_build_19.3.6.4.log)
 * jinterface     : No Java compiler found

APPLICATIONS INFORMATION (See: /home/nick/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3.6.4/otp_build_19.3.6.4.log)
 * wx             : wxWidgets not found, wx will NOT be usable

DOCUMENTATION INFORMATION (See: /home/nick/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3.6.4/otp_build_19.3.6.4.log)
 * documentation  : 
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Erlang/OTP 19.3.6.4 (asdf_19.3.6.4) has been successfully built
Installing Erlang/OTP 19.3.6.4 (asdf_19.3.6.4) in /home/nick/.asdf/installs/erlang/19.3.6.4...
You can activate this installation running the following command:
. /home/nick/.asdf/installs/erlang/19.3.6.4/activate
Later on, you can leave the installation typing:
kerl_deactivate
Cleaning up compilation products for 
Cleaned up compilation products for  under /home/nick/.asdf/plugins/erlang/kerl-home/builds

Erlang 19.3.6.4 has been installed. Activate globally with:

    asdf global erlang 19.3.6.4

Activate locally in the current folder with:

    asdf local erlang 19.3.6.4

$ asdf install
erlang 19.3.6.4 is already installed
Downloading ruby-build...
Cloning into 'ruby-build-source'...
remote: Enumerating objects: 274, done.
remote: Counting objects: 100% (274/274), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 9554 (delta 223), reused 99 (delta 68), pack-reused 9280
Receiving objects: 100% (9554/9554), 2.01 MiB | 1.15 MiB/s, done.
Resolving deltas: 100% (6232/6232), done.
Checking connectivity... done.
Note: checking out 'v20181019'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 74e2d7c... Merge pull request #1244 from devinrm/dm-bump-version-to-2018-10-19
Downloading ruby-2.2.9.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.9.tar.bz2
Installing ruby-2.2.9...

WARNING: ruby-2.2.9 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

Installed ruby-2.2.9 to /home/nick/.asdf/installs/ruby/2.2.9



### Expected behavior

Both tools should get install on a single `asdf install` run.

### Actual behavior

One tool installed at a time.

### Environment

**OS**:
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**asdf version**:
$ asdf help
version: v0.6.2

**Comment by Stratus3D** [comment] 2018-12-26 14:19
Closing since this is a duplicate of #269 and https://github.com/asdf-vm/asdf-erlang/issues/57.

**Closed by Stratus3D** 2018-12-26 14:19 UTC

**Comment by dbodow** [comment] 2019-03-26 21:03
@Stratus3D Facing the https://github.com/asdf-vm/asdf-erlang/issues/57 issue too, but wanted to point out that there's maybe an `asdf` issue here in addition to the `asdf-erlang` issue. I would expect that asdf plugins shouldn't be able to interrupt other plugins' installation processes, or if they are allowed to, then `asdf` should print a failure/interrupt message before aborting subsequent installs. A big problem for me here was that there wasn't any logging from `asdf install` to track down this issue.

Happy to open that up as a different issue for discussion if you think that's better, but arguably it's already been logged as this and other closed duplicates here, just with different expected behavior. Cheers!
