### ISSUE TITLE
bug: Running `asdf local` in $HOME dir, is like running `asdf global`

### ISSUE THREAD

**Issue by eksperimental** [asdf-vm/asdf#1134] opened 2021-12-21 17:37 UTC
### Describe the Bug

This is due to the fact that $HOME/.tool-versions is the global config file.

I think the file should be named .global.tool-versions or something that can make it different from the regular .tool-versions.

If this is not possible due to a design limitation, placing the master file in a subfolder not as common as $HOME will work better, such as $HOME/.config/asdf/.tool-versions

### Steps to Reproduce

1. cd $HOME
2. asdf local elixir latest

### Expected Behaviour

to not to overwrite the global version

### Actual Behaviour

It defines global version

### Environment

```shell
ASDF VERSION:
v0.8.1
```

**Comment by Stratus3D** [comment] 2021-12-21 19:57
The whole local/global concept was made up by a contributor a while after asdf's version resolution behavior with `.tool-version` files was created. The `asdf global` command was added for convenience. I agree it's a poor name, and I personally don't see a benefit to it. I don't consider it a bug though. However, I'm not sure we can just remove this command or change it's behavior without expecting some complaints. Being that this isn't an actual bug it's pretty low priority for me.

**Comment by eksperimental** [comment] 2021-12-21 20:00
I disagree.
The localtion of .tool-version is an implementation detail that the end user does not need to know.
If changing the global version by running  a local command in such a common place as the home directory, which is the default directory when you open up a shell, I will consider it a bug.

**Comment by jthegedus** [comment] 2021-12-23 05:25
I agree with @Stratus3D that I do not consider this a bug.

`asdf help` could be more clear about the difference between `global` and `local` as the docs are:
- Global defaults are managed in `$HOME/.tool-versions`
- Local versions are defined in the `$PWD/.tool-versions`

If you are in `$HOME` directory, `global` and `local` are the same and **with the above information this is not a bug**.

I suggest we improve the `asdf help` output to show the `global` association with `$HOME` and `local` association with `$PWD`.

---

Side notes:

`global` was added in #46 and inspired by `rbenv`. The characteristics of the feature are different however:

- local are `$PWD/.ruby-version`
- global are in `$HOME/.rbenv/version`
- automatically defaults to the `system` version when global is absent 

IMO the concept of "global" and "local" is misleading since the version of a tool is determined by traversing `$PWD` to `/` and reading `.tool-versions` until the nearest version for the desired tool is set. So you can end up using a version that is neither configured with `local` (as it would resolve in current dir) or `global`, making the commands seemingly incomplete as there's no way to set a version in a parent directory which does influence the set of tool versions resolved.

**Comment by eksperimental** [comment] 2021-12-23 05:50
Seems like `rbenv` does not suffer from this issue. I wonder what was the decision behind for using the same file names that local and global will write to.

**Comment by jthegedus** [comment] 2022-07-17 14:39
The concept of `global` `.tool-versions` and how `.tool-versions` is resolved when executed has caused confusion. Feature https://github.com/asdf-vm/asdf/pull/1295 "custom global tool-versions location" was initially implemented without considering the impact on the walk up the directory tree because it is not clear that `global ` isn't special.

**Comment by jthegedus** [comment] 2022-07-17 14:40
I am going to close this Issue as it is not a bug.

Feel free to open a new Issue proposing the "implementation of a true, user-definable-location `global` `.tool-versions`"

**Closed by jthegedus** 2022-07-17 14:40 UTC
